"""What this repository has actually certified, ranked, with how to re-check it.

The point is not the list. The point is the third column: every row carries a
command that re-establishes that one claim from scratch, in about a second. A
certification a reader cannot cheaply reproduce is a claim of authority, which
is the thing this repository exists not to make.

Ranking is by verification tier and nothing else — not by how important the
claim looks, not by which document states it, not by how much of the corpus
repeats it.
"""

from __future__ import annotations

import shlex
from dataclasses import dataclass
from pathlib import Path

from . import check_cache
from .frontier import lean_declarations
from .invariants import SUITES

ROOT = Path(__file__).resolve().parents[2]
LEAN_DIR = ROOT / "lean" / "Workhouse"

TIER_LABEL = {
    0: "T0 — proof-checked",
    1: "T1 — re-derived exactly",
    2: "T2 — float agreement within a stated tolerance",
}

TIER_MEANING = {
    0: (
        "Lean 4 compiles it from explicit definitions with no `sorry` and only "
        "`propext`, `Classical.choice`, `Quot.sound`. Nothing a document says "
        "can weaken this."
    ),
    1: (
        "Re-derived symbolically from the definitions the corpus states, in "
        "exact rationals. Strong, and still only as good as the definitions: a "
        "T1 pass certifies the arithmetic, not the modelling."
    ),
    2: (
        "Floating-point agreement inside a tolerance printed in the detail "
        "line. Read the tolerance before quoting the claim — numerical "
        "agreement is not proof, and one of these checks exists precisely "
        "because a corpus tolerance was quoted tighter than its own data."
    ),
}


@dataclass(frozen=True)
class Claim:
    tier: int
    name: str
    where: str
    reproduce: str
    section: str = ""
    suite: str = ""
    detail: str = ""
    passing: bool = True


def lean_claims() -> list[Claim]:
    """Theorem names from the Lean tree, with the file and line each sits on.

    Public because ``claims.py`` reuses it to give every theorem a catalogue
    record. The scrape is `frontier.lean_declarations`; this adds the tier and
    the re-check command.
    """
    # The scrape itself is `frontier.lean_declarations`, which owns the one
    # pattern that knows attributes and `private` precede the keyword. This
    # function used to carry its own copy; when only one copy was widened the
    # two T0 counts disagreed by exactly the three `@[simp] theorem`s.
    return [
        Claim(
            tier=0,
            name=name,
            where=f"{rel}:{n}",
            reproduce="make lean",
            suite="lean core",
        )
        for rel, n, name in lean_declarations()
    ]


def _check_claims() -> list[Claim]:
    out: list[Claim] = []
    cache = check_cache.CheckCache()
    for suite in SUITES:
        for r in suite.run(cache=cache):
            out.append(
                Claim(
                    tier=r.tier,
                    name=r.name,
                    where=r.source,
                    reproduce=f"workhouse verify --only {shlex.quote(r.name)}",
                    section=r.section,
                    suite=suite.name,
                    detail=r.detail,
                    passing=r.passed,
                )
            )
    return out


def collect() -> list[Claim]:
    """Every certified claim, strongest tier first."""
    claims = lean_claims() + _check_claims()
    return sorted(claims, key=lambda c: (c.tier, c.suite, c.name))


def render(claims: list[Claim] | None = None) -> str:
    claims = claims if claims is not None else collect()
    out: list[str] = []
    w = out.append

    w("# Certified results")
    w("")
    w("**Generated by `workhouse certified`. Do not edit — regenerate.**")
    w("")
    w("Ranked by verification tier and nothing else. Every row carries the")
    w("command that re-establishes that one claim from scratch — a certification")
    w("you cannot cheaply reproduce is just a claim of authority.")
    w("")
    w("Start here:")
    w("")
    w("```bash")
    w("make verify                       # all of T1 and T2, a few seconds")
    w("make lean                         # all of T0 (needs elan)")
    w("workhouse verify --tier 1         # only the exact re-derivations")
    w("workhouse verify --only 'h_4^side'   # one claim, with its numbers")
    w("```")
    w("")
    failing = [c for c in claims if not c.passing]
    if failing:
        w(f"**{len(failing)} checks are failing.** They are marked below.")
        w("")

    for tier in (0, 1, 2):
        rows = [c for c in claims if c.tier == tier]
        if not rows:
            continue
        w(f"## {TIER_LABEL[tier]} — {len(rows)}")
        w("")
        w(TIER_MEANING[tier])
        w("")
        current = None
        for c in rows:
            if c.suite != current:
                current = c.suite
                w(f"**{current}**")
                w("")
            mark = "" if c.passing else " **[FAILING]**"
            cite = f" · {c.section}" if c.section else ""
            w(f"- `{c.name}`{mark}")
            w(f"  - {c.where}{cite}")
            w(f"  - `{c.reproduce}`")
        w("")

    w("## What is not here")
    w("")
    w("Everything else in the corpus. `theory/` is roughly 2,500 lines of")
    w("governing statement and `corpus-import/` is 928 files; what this page")
    w("lists is what has been re-derived, which is a small fraction of what has")
    w("been asserted. That gap is the work, not a defect — see `FRONTIER.md`")
    w("§5 for what would close parts of it.")
    w("")
    w("A claim's absence from this page means nobody has checked it yet. It does")
    w("not mean it is wrong.")

    return "\n".join(out) + "\n"


def write(path: Path | None = None) -> Path:
    target = path or (ROOT / "CERTIFIED.md")
    target.write_text(render(), encoding="utf-8", newline="\n")
    return target
