"""Claims and symbols as machine-readable records.

Two files, both generated into ``index/``:

* ``claims.jsonl`` -- one record per claim this repository can point at: every
  invariant check, every registered constant, every ledger entry, every
  literature edge, every Lean theorem, every ADR.
* ``symbols.jsonl`` -- the curated aliases from ``ledger/symbols.yaml``, joined
  to the claims that mention them.

A third file, ``graph.jsonl``, holds the typed edges between these records; it
is generated by ``graph.py`` from the same sources.

**Nothing here is authored at generation time.** Every field is copied from a
curated source: a check's own name and detail line, a ``Constant``'s note and
provenance, a ledger entry's text. There is deliberately no ``summary`` or
``topics`` field, because a generated one-line gloss of a claim nobody wrote is
a place for an error to enter that no test can catch -- and it would then read
like an index rather than like a guess.
"""

from __future__ import annotations

import json
import re
from dataclasses import asdict, dataclass, field
from fractions import Fraction
from pathlib import Path
from typing import Any

import yaml

from . import certified as certified_mod
from . import constants as K
from . import ledger as ledger_mod
from . import literature as literature_mod
from .invariants import SUITES

ROOT = Path(__file__).resolve().parents[2]
INDEX_DIR = ROOT / "index"
CLAIMS = INDEX_DIR / "claims.jsonl"
SYMBOLS = INDEX_DIR / "symbols.jsonl"
SYMBOL_SOURCE = ROOT / "ledger" / "symbols.yaml"
THEOREM_SOURCE = ROOT / "ledger" / "theorems.yaml"
PROVENANCE_SOURCE = ROOT / "ledger" / "provenance.yaml"
DECISIONS_DIR = ROOT / "docs" / "decisions"

KINDS = (
    "check",
    "constant",
    "contradiction",
    "gap",
    "register",
    "unifying",
    "paper",
    "theorem",
    "decision",
    "document",
)

#: A ledger id anywhere in free text. Case-sensitive on purpose: `u4` in
#: "O(u^4)" and `U` in "SU(4)" must not read as claim ids.
LEDGER_ID = re.compile(r"\b([CGRU]\d+)\b")
#: An "ADR NNNN" reference in free text or a status paragraph.
ADR_REF = re.compile(r"\bADR\s*(\d{4})\b")


@dataclass
class Claim:
    id: str
    kind: str
    #: The claim in the words of whoever curated it. Never generated here.
    statement: str
    #: 0-3, or None where the record is not a verification claim at all.
    tier: int | None = None
    #: Exact value as "p/q" where the claim has one, else the float's repr.
    value: str | None = None
    #: Float form, so a search by decimal prefix can reach it.
    decimal: float | None = None
    where: str = ""
    cites: str = ""
    reproduce: str = ""
    status: str = ""
    evidence: str = ""
    detail: str = ""
    related: list[str] = field(default_factory=list)


def _as_value(value: Any) -> tuple[str | None, float | None]:
    """Exact string and float form, keeping the exact/float distinction visible.

    A sympy Rational renders as "p/q"; a float renders as its repr. The two are
    never merged, because a float that reads as exact is the most dangerous bug
    in this repository.
    """
    if value is None:
        return None, None
    try:
        if hasattr(value, "p") and hasattr(value, "q"):  # sympy Rational
            return f"{value.p}/{value.q}", float(value)
        if isinstance(value, Fraction):
            return f"{value.numerator}/{value.denominator}", float(value)
        if isinstance(value, float):
            return repr(value), value
        if isinstance(value, int):
            return str(value), float(value)
        if getattr(value, "free_symbols", None):
            return str(value), None  # symbolic in N or L; no single float
        return str(value), float(value)
    except (TypeError, ValueError):
        return str(value), None


def _slug(text: str) -> str:
    keep = [c if c.isalnum() else "-" for c in text.lower()]
    return "".join(keep).strip("-").replace("--", "-")[:40]


def check_id(suite_name: str, check_name: str) -> str:
    """The catalogue id of one registered check. The single place the format lives."""
    return f"CHK:{_slug(suite_name)}:{_slug(check_name)}"


def load_theorems(path: Path | None = None) -> list[dict[str, Any]]:
    return yaml.safe_load((path or THEOREM_SOURCE).read_text())["theorems"]


def load_provenance(path: Path | None = None) -> list[dict[str, Any]]:
    """The curated originating-document register (ledger/provenance.yaml)."""
    return yaml.safe_load((path or PROVENANCE_SOURCE).read_text())["documents"]


def _adr_status(text: str) -> str:
    """The status paragraph of an ADR, in either of the two formats in use."""
    m = re.search(r"^## Status\s*\n+(.*?)(?:\n##|\Z)", text, re.S | re.M)
    if m:
        return " ".join(m.group(1).split())
    m = re.search(r"\*\*Status:\*\*\s*(.+)", text)
    return " ".join(m.group(1).split()) if m else ""


def decisions() -> list[dict[str, Any]]:
    """The ADRs as records: title, status, and every id each one references.

    ``amends`` and ``retracts`` are read from the status paragraph only — an
    ADR body discussing another ADR does not amend it.
    """
    out: list[dict[str, Any]] = []
    for path in sorted(DECISIONS_DIR.glob("*.md")):
        text = path.read_text()
        lines = text.splitlines()
        title = lines[0].lstrip("#").strip() if lines else path.stem
        status = _adr_status(text)
        own_id = f"ADR:{path.name[:4]}"
        amends = [f"ADR:{n}" for n in re.findall(r"\bAmends\b[^.\n]*?\bADR\s*(\d{4})", status)]
        retracts = [f"ADR:{n}" for n in re.findall(r"\bRetracts\b[^.\n]*?\bADR\s*(\d{4})", status)]
        mentions = set(LEDGER_ID.findall(text)) | {f"ADR:{n}" for n in ADR_REF.findall(text)}
        mentions -= {own_id, *amends, *retracts}
        out.append(
            {
                "id": own_id,
                "where": str(path.relative_to(ROOT)),
                "title": title,
                "status": status,
                "mentions": sorted(mentions),
                "amends": amends,
                "retracts": retracts,
            }
        )
    return out


def collect() -> list[Claim]:
    out: list[Claim] = []

    for suite in SUITES:
        for result in suite.run():
            out.append(
                Claim(
                    id=check_id(suite.name, result.name),
                    kind="check",
                    statement=result.name,
                    tier=result.tier,
                    where=f"src/workhouse/invariants.py:{result.line}",
                    cites=result.section,
                    reproduce=f"workhouse verify --only {result.name!r}",
                    detail=result.detail,
                    status="passing" if result.passed else "FAILING",
                )
            )

    for constant in K.REGISTRY:
        exact, decimal = _as_value(constant.value)
        out.append(
            Claim(
                id=f"CONST:{constant.name}",
                kind="constant",
                statement=constant.note or constant.name,
                # A registered constant is T3 on its own: the registry records
                # what the corpus says. Whatever checks it supplies the tier.
                tier=3,
                value=exact,
                decimal=decimal,
                where="src/workhouse/constants.py",
                cites=constant.source,
                status=constant.status,
                evidence=constant.evidence,
            )
        )

    # Module-level constants that REGISTRY does not curate. They carry no
    # status, evidence, or note -- which is exactly the point of recording them:
    # a name that search must reach, and a provenance gap someone should close.
    curated = {c.name for c in K.REGISTRY}
    for name in sorted(n for n in dir(K) if n.isupper() and not n.startswith("_")):
        if name in curated:
            continue
        raw = getattr(K, name)
        # Sets are closed vocabularies, not values, and their repr ordering is
        # not stable across runs -- which would make this file spuriously
        # "stale" on every regeneration.
        if isinstance(raw, (set, frozenset, dict, str)):
            continue
        if isinstance(raw, tuple):
            parts = [_as_value(v)[0] for v in raw]
            if any(part is None for part in parts):
                continue
            exact, decimal = ", ".join(parts), None
        else:
            exact, decimal = _as_value(raw)
        if exact is None:
            continue
        out.append(
            Claim(
                id=f"CONST:{name}",
                kind="constant",
                statement=name,
                tier=3,
                value=exact,
                decimal=decimal,
                where="src/workhouse/constants.py",
                status="module-level, not in REGISTRY",
            )
        )

    led = ledger_mod.load()
    for entry in led.contradictions:
        out.append(
            Claim(
                id=entry["id"],
                kind="contradiction",
                statement=entry["title"],
                tier=3,
                where="ledger/contradictions.yaml",
                cites=entry.get("section", ""),
                status=entry["status"],
                detail=" ".join(str(entry.get("resolution", "")).split()),
                related=sorted(entry.get("blocks", [])),
            )
        )
    for entry in led.gaps:
        out.append(
            Claim(
                id=entry["id"],
                kind="gap",
                statement=entry["title"],
                tier=3,
                where="ledger/gaps.yaml",
                status=f"tier {entry['tier']}"
                + (" load-bearing" if entry.get("load_bearing") else ""),
                detail=" ".join(str(entry.get("detail", "")).split()),
                related=sorted(entry.get("resolves", []) + entry.get("unblocks", [])),
            )
        )
    for entry in led.register:
        out.append(
            Claim(
                id=entry["id"],
                kind="register",
                statement=entry["title"],
                tier=3,
                where="ledger/governing_register.yaml",
                cites="MASTER_THEORY_UNIFIED v4.3 §14",
                detail=" ".join(str(entry["text"]).split()),
                related=sorted(entry["contradictions"] + entry["gaps"]),
            )
        )
    for entry in led.unifying_candidates:
        out.append(
            Claim(
                id=entry["id"],
                kind="unifying",
                statement=" ".join(str(entry["statement"]).split()),
                tier=3,
                where="ledger/gaps.yaml",
                status=entry["status"],
                detail="FALSIFIER: " + " ".join(str(entry["falsifier"]).split()),
                related=sorted(entry.get("supported_by", [])),
            )
        )

    for paper in literature_mod.load().papers:
        for edge in paper.get("bears_on", []):
            out.append(
                Claim(
                    id=f"LIT:{paper['id']}:{edge['target']}",
                    kind="paper",
                    statement=(
                        f"{paper['title']} ({paper['year']}) {edge['relation']} {edge['target']}"
                    ),
                    tier=3,
                    where="literature/index.yaml",
                    cites=paper.get("doi") or paper.get("arxiv") or "",
                    status=edge["status"],
                    detail=" ".join(str(edge["detail"]).split()),
                    related=[edge["target"]],
                )
            )

    # The T0 layer. The scrape supplies name and location; everything else is
    # transcribed by hand in ledger/theorems.yaml, following the symbols.yaml
    # pattern: judgement in a curated file, the join derived, validation
    # mechanical (tests/test_graph.py).
    notes = {t["name"]: t for t in load_theorems()}
    chk_ids: dict[str, list[str]] = {}
    for suite in SUITES:
        for name, _section, _tier, _fn in suite.checks:
            chk_ids.setdefault(name, []).append(check_id(suite.name, name))
    for lean in certified_mod.lean_claims():
        note = notes.get(lean.name, {})
        value = note.get("value")
        related = set(note.get("formalizes", []))
        for check_name in note.get("promotes", []):
            related.update(chk_ids.get(check_name, []))
        out.append(
            Claim(
                id=f"LEAN:{lean.name}",
                kind="theorem",
                statement=" ".join(str(note.get("statement", lean.name)).split()),
                tier=0,
                value=value,
                decimal=float(Fraction(value)) if value is not None else None,
                where=lean.where,
                reproduce="make lean",
                related=sorted(related),
            )
        )

    for adr in decisions():
        first_sentence = adr["status"].split(".")[0].strip()
        out.append(
            Claim(
                id=adr["id"],
                kind="decision",
                statement=adr["title"],
                tier=3,
                where=adr["where"],
                status=first_sentence,
                detail=adr["status"],
                related=sorted({*adr["mentions"], *adr["amends"], *adr["retracts"]}),
            )
        )

    # Originating corpus documents. Still T3 — the register machine-checks the
    # provenance (pin, quote, line), never the truth of what the document says.
    for doc in load_provenance():
        out.append(
            Claim(
                id=f"DOC:{doc['id']}",
                kind="document",
                statement=" ".join(str(doc["meaning"]).split()),
                tier=3,
                where=f"corpus-import/{doc['path']}",
                cites="ledger/provenance.yaml",
                status=doc["role"],
                detail="; ".join(
                    f"originates {o['target']}: {o['what']}" for o in doc["originates"]
                ),
                related=sorted({o["target"] for o in doc["originates"]}),
            )
        )

    return out


def load_symbols(path: Path | None = None) -> list[dict[str, Any]]:
    return yaml.safe_load((path or SYMBOL_SOURCE).read_text())["symbols"]


def symbol_records(claims: list[Claim] | None = None) -> list[dict[str, Any]]:
    """Curated aliases, joined to the claims that name them."""
    claims = claims if claims is not None else collect()
    records = []
    for symbol in load_symbols():
        haystacks = {
            symbol["canonical"],
            *symbol.get("code_names", []),
            *symbol.get("corpus_spellings", []),
        }
        mentions = sorted(
            c.id for c in claims if any(h and h in f"{c.statement} {c.detail}" for h in haystacks)
        )
        record = dict(symbol)
        record["mentioned_by"] = mentions
        record["search_keys"] = sorted(
            {
                *haystacks,
                *symbol.get("values", []),
                symbol["id"],
            }
        )
        records.append(record)
    return records


def write(directory: Path | None = None) -> tuple[Path, Path]:
    target = directory or INDEX_DIR
    target.mkdir(parents=True, exist_ok=True)
    claims = collect()
    (target / "claims.jsonl").write_text(
        "".join(json.dumps(asdict(c), sort_keys=True) + "\n" for c in claims)
    )
    (target / "symbols.jsonl").write_text(
        "".join(json.dumps(s, sort_keys=True) + "\n" for s in symbol_records(claims))
    )
    return target / "claims.jsonl", target / "symbols.jsonl"
