"""Claims and symbols as machine-readable records.

Two files, both generated into ``index/``:

* ``claims.jsonl`` -- one record per claim this repository can point at: every
  invariant check, every registered constant, every ledger entry, every
  literature edge, every Lean theorem, every ADR.
* ``symbols.jsonl`` -- the curated aliases from ``ledger/symbols.yaml``, joined
  to the claims that mention them.

A third file, ``graph.jsonl``, holds the typed edges between these records; it
is generated by ``graph.py`` from the same sources.

**Nothing here is authored at generation time.** Every field is copied from a
curated source: a check's own name and detail line, a ``Constant``'s note and
provenance, a ledger entry's text. There is deliberately no ``summary`` or
``topics`` field, because a generated one-line gloss of a claim nobody wrote is
a place for an error to enter that no test can catch -- and it would then read
like an index rather than like a guess.
"""

from __future__ import annotations

import hashlib
import json
import re
from dataclasses import asdict, dataclass, field
from fractions import Fraction
from pathlib import Path
from typing import Any

import yaml

from . import certified as certified_mod
from . import constants as K
from . import ledger as ledger_mod
from . import literature as literature_mod
from . import notes as notes_mod
from .invariants import SUITES

ROOT = Path(__file__).resolve().parents[2]
INDEX_DIR = ROOT / "index"
CLAIMS = INDEX_DIR / "claims.jsonl"
SYMBOLS = INDEX_DIR / "symbols.jsonl"
SYMBOL_SOURCE = ROOT / "ledger" / "symbols.yaml"
THEOREM_SOURCE = ROOT / "ledger" / "theorems.yaml"
PROVENANCE_SOURCE = ROOT / "ledger" / "provenance.yaml"
DECISIONS_DIR = ROOT / "docs" / "decisions"

KINDS = (
    "check",
    "constant",
    "contradiction",
    "gap",
    "register",
    "unifying",
    "paper",
    "theorem",
    "decision",
    "document",
    "citation",
    "archive",
    "note",
    "run",
    "route",
)

#: A ledger id anywhere in free text. Case-sensitive on purpose: `u4` in
#: "O(u^4)" and `U` in "SU(4)" must not read as claim ids.
LEDGER_ID = re.compile(r"\b([CGRU]\d+)\b")
#: An "ADR NNNN" reference in free text or a status paragraph.
ADR_REF = re.compile(r"\bADR\s*(\d{4})\b")


@dataclass
class Claim:
    id: str
    kind: str
    #: The claim in the words of whoever curated it. Never generated here.
    statement: str
    #: 0-3, or None where the record is not a verification claim at all.
    tier: int | None = None
    #: Exact value as "p/q" where the claim has one, else the float's repr.
    value: str | None = None
    #: Float form, so a search by decimal prefix can reach it.
    decimal: float | None = None
    where: str = ""
    cites: str = ""
    reproduce: str = ""
    status: str = ""
    evidence: str = ""
    detail: str = ""
    related: list[str] = field(default_factory=list)


def _as_value(value: Any) -> tuple[str | None, float | None]:
    """Exact string and float form, keeping the exact/float distinction visible.

    A sympy Rational renders as "p/q"; a float renders as its repr. The two are
    never merged, because a float that reads as exact is the most dangerous bug
    in this repository.
    """
    if value is None:
        return None, None
    try:
        if hasattr(value, "p") and hasattr(value, "q"):  # sympy Rational
            return f"{value.p}/{value.q}", float(value)
        if isinstance(value, Fraction):
            return f"{value.numerator}/{value.denominator}", float(value)
        if isinstance(value, float):
            return repr(value), value
        if isinstance(value, int):
            return str(value), float(value)
        if getattr(value, "free_symbols", None):
            return str(value), None  # symbolic in N or L; no single float
        return str(value), float(value)
    except (TypeError, ValueError):
        return str(value), None


def _slug(text: str) -> str:
    keep = [c if c.isalnum() else "-" for c in text.lower()]
    return "".join(keep).strip("-").replace("--", "-")[:40]


def _ident(text: str) -> str:
    """A slug that cannot collide by truncation.

    ``_slug`` caps at 40 characters, and check names here are long and
    formulaic -- 158 of 193 hit that cap, as do 7 of 20 suite names. Two names
    agreeing in their first 40 characters would therefore produce ONE id, and
    a graph keyed on ids would silently merge two distinct checks into a node
    carrying both their edges. Nothing would fail; the graph would just be
    wrong. ``note_id`` already learned this on 24 colliding archive paths and
    fixed it with a digest suffix; this is the same fix for the other half of
    the catalogue.

    Untruncated names keep a clean, readable id -- the suffix appears only
    where the cap actually bit, so it marks exactly the ids that needed it.
    """
    slug = _slug(text)
    if len(slug) < 40:
        return slug
    return f"{slug}-{hashlib.sha256(text.encode('utf-8')).hexdigest()[:6]}"


def check_id(suite_name: str, check_name: str) -> str:
    """The catalogue id of one registered check. The single place the format lives."""
    return f"CHK:{_ident(suite_name)}:{_ident(check_name)}"


def route_id(gap_id: str, step: str) -> str:
    """The catalogue id of one plan step under a gap -- a route.

    A route is an attempt at a gap with a recorded state (untried, live,
    dead, done) and, when closed, the run or check that closed it. Making it a
    node is what lets `why G3` say which attempts are dead instead of leaving
    that to a reader of run READMEs.
    """
    return f"ROUTE:{gap_id}:{_ident(step)}"


#: A ``\chk{...}`` label in a manuscript source, with LaTeX escapes undone.
#: The body may contain ``\^{}`` (a standalone circumflex), so a ``[^}]*``
#: body would stop at the wrong brace; balanced empty groups are allowed.
_CHK_LABEL = re.compile(r"\\chk\{((?:[^{}]|\{\})*)\}")


def chk_labels(source: str) -> list[str]:
    r"""Every ``\chk`` label in a pinned edition, in order, as check names.

    One parser for the manuscript guard and the graph, so the two can never
    disagree about what a paper labels.
    """
    return [
        m.replace("\\_", "_").replace("\\^{}", "^").replace("\\^", "^")
        for m in _CHK_LABEL.findall(source)
    ]


def _yield_value(text: str) -> tuple[str, float | None]:
    """A yielded value's exact string and float, as `_as_value` would give."""
    try:
        exact = Fraction(text)
    except (ValueError, ZeroDivisionError):
        return text, None  # symbolic in N or L
    if exact.denominator == 1:
        return str(exact.numerator), float(exact)
    return f"{exact.numerator}/{exact.denominator}", float(exact)


def note_id(archive_id: str, row: dict[str, Any]) -> str:
    """The catalogue id of one archived note document.

    Keyed on the path so a reader can search for the filename they remember,
    with a short digest suffix because slugs truncate at 40 characters and 24
    of these archives' paths collide once truncated ("00_INDEX.md" appears in
    many folders). Substring search still finds the filename.
    """
    stem = row["paths"][0].rsplit("/", 1)[-1]
    return f"NOTE:{archive_id}:{_slug(stem)}-{row['digest'][:6]}"


def load_runs(path: Path | None = None) -> list[dict[str, Any]]:
    """The run register: one entry per pinned run record in runs/."""
    path = path or ROOT / "runs" / "index.yaml"
    if not path.exists():
        return []
    return yaml.safe_load(path.read_text(encoding="utf-8"))["runs"]


def load_theorems(path: Path | None = None) -> list[dict[str, Any]]:
    return yaml.safe_load((path or THEOREM_SOURCE).read_text(encoding="utf-8"))["theorems"]


def load_document_aliases(path: Path | None = None) -> list[dict[str, Any]]:
    """The citation-alias register (ledger/documents.yaml)."""
    source = path or ROOT / "ledger" / "documents.yaml"
    return yaml.safe_load(source.read_text(encoding="utf-8"))["aliases"]


def load_provenance(path: Path | None = None) -> list[dict[str, Any]]:
    """The curated originating-document register (ledger/provenance.yaml)."""
    return yaml.safe_load((path or PROVENANCE_SOURCE).read_text(encoding="utf-8"))["documents"]


def _adr_status(text: str) -> str:
    """The status paragraph of an ADR, in either of the two formats in use."""
    m = re.search(r"^## Status\s*\n+(.*?)(?:\n##|\Z)", text, re.S | re.M)
    if m:
        return " ".join(m.group(1).split())
    m = re.search(r"\*\*Status:\*\*\s*(.+)", text)
    return " ".join(m.group(1).split()) if m else ""


def decisions() -> list[dict[str, Any]]:
    """The ADRs as records: title, status, and every id each one references.

    ``amends`` and ``retracts`` are read from the status paragraph only — an
    ADR body discussing another ADR does not amend it.
    """
    out: list[dict[str, Any]] = []
    for path in sorted(DECISIONS_DIR.glob("*.md")):
        text = path.read_text(encoding="utf-8")
        lines = text.splitlines()
        title = lines[0].lstrip("#").strip() if lines else path.stem
        status = _adr_status(text)
        own_id = f"ADR:{path.name[:4]}"
        amends = [f"ADR:{n}" for n in re.findall(r"\bAmends\b[^.\n]*?\bADR\s*(\d{4})", status)]
        retracts = [f"ADR:{n}" for n in re.findall(r"\bRetracts\b[^.\n]*?\bADR\s*(\d{4})", status)]
        mentions = set(LEDGER_ID.findall(text)) | {f"ADR:{n}" for n in ADR_REF.findall(text)}
        mentions -= {own_id, *amends, *retracts}
        out.append(
            {
                "id": own_id,
                "where": path.relative_to(ROOT).as_posix(),
                "title": title,
                "status": status,
                "mentions": sorted(mentions),
                "amends": amends,
                "retracts": retracts,
            }
        )
    return out


def collect() -> list[Claim]:
    out: list[Claim] = []

    for suite in SUITES:
        for result in suite.run():
            chk = check_id(suite.name, result.name)
            out.append(
                Claim(
                    id=chk,
                    kind="check",
                    statement=result.name,
                    tier=result.tier,
                    where=result.source,
                    cites=result.section,
                    reproduce=f"workhouse verify --only {result.name!r}",
                    detail=result.detail,
                    status="passing" if result.passed else "FAILING",
                    related=sorted(result.rests_on),
                )
            )
            # A value a check yields is a constant with the check as its
            # origin: searchable by value, and carrying the check's tier
            # while the check passes. A failing check's yields are T3 --
            # recorded, not established.
            for name, text in sorted(result.yields.items()):
                exact, decimal = _yield_value(text)
                out.append(
                    Claim(
                        id=f"CONST:{name}",
                        kind="constant",
                        statement=f"{name}, yielded by the check {result.name!r}",
                        tier=result.tier if result.passed else 3,
                        value=exact,
                        decimal=decimal,
                        where=result.source,
                        cites=result.section,
                        reproduce=f"workhouse verify --only {result.name!r}",
                        status="yielded by a passing check"
                        if result.passed
                        else "yielded by a FAILING check",
                        related=[chk],
                    )
                )

    for constant in K.REGISTRY:
        exact, decimal = _as_value(constant.value)
        out.append(
            Claim(
                id=f"CONST:{constant.name}",
                kind="constant",
                statement=constant.note or constant.name,
                # A registered constant is T3 on its own: the registry records
                # what the corpus says. Whatever checks it supplies the tier.
                tier=3,
                value=exact,
                decimal=decimal,
                where="src/workhouse/constants.py",
                cites=constant.source,
                status=constant.status,
                evidence=constant.evidence,
            )
        )

    # Module-level constants that REGISTRY does not curate. They carry no
    # status, evidence, or note -- which is exactly the point of recording them:
    # a name that search must reach, and a provenance gap someone should close.
    curated = {c.name for c in K.REGISTRY}
    for name in sorted(n for n in dir(K) if n.isupper() and not n.startswith("_")):
        if name in curated:
            continue
        raw = getattr(K, name)
        # Sets are closed vocabularies, not values, and their repr ordering is
        # not stable across runs -- which would make this file spuriously
        # "stale" on every regeneration. Bare Symbols (N, L) are coordinates,
        # not constants, and their "value" is their own name.
        if isinstance(raw, (set, frozenset, dict, str)) or getattr(raw, "is_Symbol", False):
            continue
        if isinstance(raw, tuple):
            # Only tuples of actual numbers. A tuple of records (REGISTRY)
            # would otherwise emit its entire repr as a "value" — a 2 KB blob
            # that substring-matches half of all queries.
            parts = [_as_value(v) for v in raw]
            if not parts or any(decimal is None for _exact, decimal in parts):
                continue
            exact, decimal = ", ".join(p[0] for p in parts), None
        else:
            exact, decimal = _as_value(raw)
        if exact is None:
            continue
        out.append(
            Claim(
                id=f"CONST:{name}",
                kind="constant",
                statement=name,
                tier=3,
                value=exact,
                decimal=decimal,
                where="src/workhouse/constants.py",
                status="module-level, not in REGISTRY",
            )
        )

    led = ledger_mod.load()
    for entry in led.contradictions:
        out.append(
            Claim(
                id=entry["id"],
                kind="contradiction",
                statement=entry["title"],
                tier=3,
                where="ledger/contradictions.yaml",
                cites=entry.get("section", ""),
                status=entry["status"],
                detail=" ".join(str(entry.get("resolution") or entry.get("notes") or "").split()),
                related=sorted(entry.get("blocks", [])),
            )
        )
    for entry in led.gaps:
        # "cost", not "tier": the gap scale is days/weeks/months/unbounded and
        # must never read as the T0-T3 verification vocabulary.
        state = entry.get("state", "open")
        status_prose = " ".join(str(entry.get("status", "")).split())
        detail = " ".join(str(entry.get("detail", "")).split())
        if state != "open" and status_prose:
            detail = f"{status_prose} · {detail}" if detail else status_prose
        out.append(
            Claim(
                id=entry["id"],
                kind="gap",
                statement=entry["title"],
                tier=3,
                where="ledger/gaps.yaml",
                status=f"cost {entry['tier']} · {state}"
                + (" load-bearing" if entry.get("load_bearing") else ""),
                detail=detail,
                related=sorted(entry.get("resolves", []) + entry.get("unblocks", [])),
            )
        )
    # Routes: one node per plan step, so an attempt has a state a query can
    # read. Everything is copied from the step's own fields.
    for entry in led.gaps:
        for step in entry.get("plan", []) or []:
            out.append(
                Claim(
                    id=route_id(entry["id"], step["step"]),
                    kind="route",
                    statement=f"{entry['id']} route: {step['step']}",
                    tier=3,
                    where="ledger/gaps.yaml",
                    cites=entry["id"],
                    status=str(step.get("state", "")),
                    detail=" ".join(str(step.get("status", "")).split()),
                    related=sorted(
                        [str(r) for r in step.get("closed_by", []) or []]
                        + [str(r) for r in step.get("cannot_decide", []) or []]
                    ),
                )
            )
    for entry in led.register:
        out.append(
            Claim(
                id=entry["id"],
                kind="register",
                statement=entry["title"],
                tier=3,
                where="ledger/governing_register.yaml",
                cites="MASTER_THEORY_UNIFIED v4.3 §14",
                detail=" ".join(str(entry["text"]).split()),
                related=sorted(entry["contradictions"] + entry["gaps"]),
            )
        )
    for entry in led.unifying_candidates:
        out.append(
            Claim(
                id=entry["id"],
                kind="unifying",
                statement=" ".join(str(entry["statement"]).split()),
                tier=3,
                where="ledger/gaps.yaml",
                status=entry["status"],
                detail="FALSIFIER: " + " ".join(str(entry["falsifier"]).split()),
                related=sorted(entry.get("supported_by", [])),
            )
        )

    lit = literature_mod.load()
    for paper in lit.papers:
        for edge in paper.get("bears_on", []):
            out.append(
                Claim(
                    id=f"LIT:{paper['id']}:{edge['target']}",
                    kind="paper",
                    statement=(
                        f"{paper['title']} ({paper['year']}) {edge['relation']} {edge['target']}"
                    ),
                    tier=3,
                    where="literature/index.yaml",
                    cites=paper.get("doi") or paper.get("arxiv") or "",
                    status=edge["status"],
                    detail=" ".join(str(edge["detail"]).split()),
                    related=[edge["target"]],
                )
            )
    # Paper-level nodes, one per indexed paper or stub, so the curated
    # citation web has endpoints to hang on. The per-edge records above stay:
    # they are the evidence claims; these are the papers themselves.
    in_degree = lit.in_degree()
    for record in lit.papers + lit.stubs:
        rid = record["id"]
        stub = rid in lit.stub_ids
        standing = "stub — cited by the web, not indexed" if stub else "indexed"
        if lit.obtained(rid):
            standing += " · pinned"
        citations = record.get("inspire_citations") or {}
        weights = f"cited in-web by {in_degree.get(rid, 0)}"
        if citations.get("count") is not None:
            weights += f"; INSPIRE {citations['count']} as of {citations.get('as_of', '')}"
        out.append(
            Claim(
                id=f"LIT:{rid}",
                kind="paper",
                statement=f"{record['title']} ({record['year']})",
                tier=3,
                where="literature/index.yaml",
                cites=record.get("doi") or record.get("arxiv") or "",
                status=standing,
                detail=f"{weights}. {' '.join(str(record.get('note', '')).split())}".strip(),
                related=sorted(
                    {e["target"] for e in record.get("bears_on", [])} | set(record.get("cites", []))
                ),
            )
        )

    # The T0 layer. The scrape supplies name and location; everything else is
    # transcribed by hand in ledger/theorems.yaml, following the symbols.yaml
    # pattern: judgement in a curated file, the join derived, validation
    # mechanical (tests/test_graph.py).
    notes = {t["name"]: t for t in load_theorems()}
    chk_ids: dict[str, list[str]] = {}
    for suite in SUITES:
        for name, _section, _tier, _fn in suite.checks:
            chk_ids.setdefault(name, []).append(check_id(suite.name, name))
    for lean in certified_mod.lean_claims():
        note = notes.get(lean.name, {})
        value = note.get("value")
        related = set(note.get("formalizes", []))
        for check_name in note.get("promotes", []):
            related.update(chk_ids.get(check_name, []))
        out.append(
            Claim(
                id=f"LEAN:{lean.name}",
                kind="theorem",
                statement=" ".join(str(note.get("statement", lean.name)).split()),
                tier=0,
                value=value,
                decimal=float(Fraction(value)) if value is not None else None,
                where=lean.where,
                reproduce="make lean",
                related=sorted(related),
            )
        )

    for adr in decisions():
        first_sentence = adr["status"].split(".")[0].strip()
        out.append(
            Claim(
                id=adr["id"],
                kind="decision",
                statement=adr["title"],
                tier=3,
                where=adr["where"],
                status=first_sentence,
                detail=adr["status"],
                related=sorted({*adr["mentions"], *adr["amends"], *adr["retracts"]}),
            )
        )

    # Citation aliases. A check cites its source by the alias
    # ledger/documents.yaml legends -- "MASTER_THEORY §4.3", "UNIFIED §0.1" --
    # and until those aliases were catalogue records there was nothing for the
    # citation to point AT, so most checks sat in the graph with no edge at
    # all. The alias is the node; the standing is the status, because citing a
    # superseded document as if current is the failure this register exists to
    # prevent.
    for alias in load_document_aliases():
        if alias.get("unresolved"):
            continue
        out.append(
            Claim(
                id=f"CITE:{alias['alias']}",
                kind="citation",
                statement=alias.get("title", alias["alias"]),
                tier=3,
                where=str(alias.get("path", "")),
                cites="ledger/documents.yaml",
                status=alias["standing"],
                detail=" ".join(str(alias.get("note", "")).split()),
            )
        )

    # Originating corpus documents. Still T3 — the register machine-checks the
    # provenance (pin, quote, line), never the truth of what the document says.
    for doc in load_provenance():
        out.append(
            Claim(
                id=f"DOC:{doc['id']}",
                kind="document",
                statement=" ".join(str(doc["meaning"]).split()),
                tier=3,
                where=f"corpus-import/{doc['path']}",
                cites="ledger/provenance.yaml",
                status=doc["role"],
                detail="; ".join(
                    f"originates {o['target']}: {o['what']}" for o in doc["originates"]
                ),
                related=sorted({o["target"] for o in doc["originates"]}),
            )
        )

    # The notes archives, and the documents inside them. Until now the
    # maintainer's own research notes were declared in ledger/notes.yaml and
    # inventoried in notes/*.jsonl, and reached the graph nowhere -- 1,689
    # documents with no node, so nothing a review said a document bears on was
    # an edge, and "which notes touch C2" had no answer the graph could give.
    #
    # Two rules keep this from becoming a promotion mechanism. Every node is
    # T3, whatever its verdict, because a verdict records a JUDGEMENT about a
    # document and never the truth of what it says. And the coefficient edges
    # are matched by VALUE -- the triage signature digits against the
    # registry's own exact numerators -- not by a name map written here, so a
    # document is linked to a constant only when it demonstrably carries that
    # constant's digits.
    notes = notes_mod.load()
    reviews = {r["digest"]: r for r in notes.reviews}
    for archive in notes.archives:
        aid = archive["id"]
        rows = notes.manifests.get(aid, [])
        reviewed = sum(1 for row in rows if row["digest"] in reviews)
        out.append(
            Claim(
                id=f"ARCHIVE:{aid}",
                kind="archive",
                statement=" ".join(str(archive["description"]).split()),
                tier=3,
                where=f"notes/{aid}.jsonl",
                cites="ledger/notes.yaml",
                status=(
                    f"{len(rows)} documents, {reviewed} reviewed, {len(rows) - reviewed} pending"
                ),
                detail=" ".join(str(archive.get("source", "")).split()),
            )
        )
        for row in rows:
            review = reviews.get(row["digest"])
            coefficients = row.get("coefficients") or []
            # A pending document with no coefficients is an inventory row and
            # nothing more; it still gets a node, because the archive edge is a
            # real relationship and a document invisible to the graph is a
            # document nobody will remember to review.
            out.append(
                Claim(
                    id=note_id(aid, row),
                    kind="note",
                    statement=(
                        " ".join(str(review["reason"]).split())
                        if review
                        else f"{row['paths'][0]} — inventoried, not yet reviewed"
                    ),
                    tier=3,
                    where=f"{aid}/{row['paths'][0]}",
                    cites="ledger/notes.yaml" if review else f"notes/{aid}.jsonl",
                    status=review["verdict"] if review else "pending",
                    evidence=review.get("imported_to", "") if review else "",
                    detail=(
                        f"sha256 {row['digest'][:12]}, {row['size']} bytes"
                        + (f"; carries {', '.join(coefficients)}" if coefficients else "")
                        + ("; erratum signature" if row.get("has_erratum") else "")
                    ),
                    related=sorted(review.get("bears_on", [])) if review else [],
                )
            )

    # The run register. A pinned run record is evidence that a computation was
    # executed and what it printed -- until 2026-08-28 the three of them were
    # cited by checks only as file-path strings, so "which runs bear on G3"
    # had no answer the graph could give. Every RUN node is T3: what a run
    # established is the citing checks' business, never the node's.
    for run in load_runs():
        out.append(
            Claim(
                id=f"RUN:{run['id']}",
                kind="run",
                statement=" ".join(str(run["title"]).split()),
                tier=3,
                where=run["dir"],
                cites="runs/index.yaml",
                status="pinned run record",
                detail=" ".join(str(run.get("detail", "")).split()),
                related=sorted(run.get("bears_on", [])),
            )
        )

    return out


def load_catalogue(path: Path | None = None) -> list[Claim]:
    """The checked-in catalogue, rehydrated without running a single check.

    ``index/claims.jsonl`` is staleness-tested, so it is current at every
    commit; a query tool (search, why, derive, branches) reads it in
    milliseconds instead of re-running every suite to rebuild what is already
    on disk. Verdicts are those of the last regeneration, which the staleness
    tests hold equal to the live ones at every commit; ``--live`` rebuilds
    for a working tree mid-edit. Falls back to a live ``collect()`` when the
    index has not been generated yet.
    """
    target = path or CLAIMS
    if not target.exists():
        return collect()
    return [
        Claim(**json.loads(line))
        for line in target.read_text(encoding="utf-8").splitlines()
        if line
    ]


def load_symbols(path: Path | None = None) -> list[dict[str, Any]]:
    return yaml.safe_load((path or SYMBOL_SOURCE).read_text(encoding="utf-8"))["symbols"]


def symbol_records(claims: list[Claim] | None = None) -> list[dict[str, Any]]:
    """Curated aliases, joined to the claims that name them."""
    claims = claims if claims is not None else collect()
    records = []
    for symbol in load_symbols():
        haystacks = {
            symbol["canonical"],
            *symbol.get("code_names", []),
            *symbol.get("corpus_spellings", []),
        }
        mentions = sorted(
            c.id for c in claims if any(h and h in f"{c.statement} {c.detail}" for h in haystacks)
        )
        record = dict(symbol)
        record["mentioned_by"] = mentions
        record["search_keys"] = sorted(
            {
                *haystacks,
                *symbol.get("values", []),
                symbol["id"],
            }
        )
        records.append(record)
    return records


def write(directory: Path | None = None) -> tuple[Path, Path]:
    target = directory or INDEX_DIR
    target.mkdir(parents=True, exist_ok=True)
    claims = collect()
    (target / "claims.jsonl").write_text(
        "".join(json.dumps(asdict(c), sort_keys=True) + "\n" for c in claims),
        encoding="utf-8",
        newline="\n",
    )
    (target / "symbols.jsonl").write_text(
        "".join(json.dumps(s, sort_keys=True) + "\n" for s in symbol_records(claims)),
        encoding="utf-8",
        newline="\n",
    )
    return target / "claims.jsonl", target / "symbols.jsonl"
