#!/usr/bin/env python3
"""Cold, dependency-free firewalls for the HODGE SU(3) O(u^4) path.

This file intentionally does *not* import or patch the historical v10a23/v10a25
runtime.  It provides two independent checks that must pass before that runtime
is touched again:

1. An exact SU(3) character-basis calculation of the one-plaquette C-odd gap
   through fourth order.  All arithmetic is ``fractions.Fraction``.
2. A layer-distance proof that a Q2-W-Q2 block first contributes at fifth
   order, so any (2,5)/(5,2) seven-occurrence Haar request in the O(u^4) path is
   evidence that an unnecessary full restricted-Hamiltonian build was reached.

Optional ``--audit PATH`` performs a conservative static scan for the concrete
regression recorded in the failed repair.  It accepts Python or Jupyter files.
Because arbitrary Python reflection and imported helpers cannot be proven safe
statically, this scan is non-authoritative and never authorizes production.  It
does not replace an executed root-path census with poisoned W22/qhaar sentinels.

Exit status is zero only when every requested gate passes.
"""

from __future__ import annotations

import argparse
import ast
import hashlib
import json
import sys
from collections import deque
from dataclasses import dataclass
from fractions import Fraction
from pathlib import Path
from typing import Iterable, Mapping, Sequence


Irrep = tuple[int, int]
Q = Fraction

ORDER = 4
EXPECTED_VACUUM = (Q(0), Q(0), Q(-3, 4), Q(-9, 32), Q(-39, 1280))
EXPECTED_AXIAL = (Q(8, 3), Q(1), Q(-1, 4), Q(-1, 16), Q(-13, 896))
EXPECTED_GAP = (Q(8, 3), Q(1), Q(1, 2), Q(7, 32), Q(143, 8960))

LAYERS = ("P", "Q1", "Q2")
LAYER_DEPTH = {name: i for i, name in enumerate(LAYERS)}
REGRESSION_SIGNATURES = {(2, 5), (5, 2)}
LEGACY_SYMBOLS = {
    "_v23c_fit_cluster",
    "_v23c_build_basis",
    "_v23c_inner",
    "qhaar",
    "_qcache",
}
DYNAMIC_LOOKUP_CALLS = {"getattr", "globals", "locals", "eval", "exec", "__import__"}
EXPECTED_A6 = {
    (0, 3),
    (0, 6),
    (1, 1),
    (1, 4),
    (2, 2),
    (3, 0),
    (3, 3),
    (4, 1),
    (6, 0),
}


class GateFailure(RuntimeError):
    """Raised when a production-safety invariant is not established."""


def fuse_fundamental(rep: Irrep) -> tuple[Irrep, ...]:
    """Return SU(3) irreps in (1,0) tensor (p,q), with unit multiplicity."""
    p, q = rep
    candidates = ((p + 1, q), (p - 1, q + 1), (p, q - 1))
    return tuple(x for x in candidates if min(x) >= 0)


def fuse_antifundamental(rep: Irrep) -> tuple[Irrep, ...]:
    """Return SU(3) irreps in (0,1) tensor (p,q), with unit multiplicity."""
    p, q = rep
    candidates = ((p, q + 1), (p + 1, q - 1), (p - 1, q))
    return tuple(x for x in candidates if min(x) >= 0)


def magnetic_neighbors(rep: Irrep) -> tuple[Irrep, ...]:
    """Character products generated by chi_3 + chi_3bar."""
    return fuse_fundamental(rep) + fuse_antifundamental(rep)


def magnetic_multiplicity(left: Irrep, right: Irrep) -> int:
    return magnetic_neighbors(right).count(left)


def electric_energy(rep: Irrep) -> Q:
    """One-plaquette H0=2*C2(p,q), normalized so E_(1,0)=8/3."""
    p, q = rep
    return Q(2 * (p * p + q * q + p * q + 3 * p + 3 * q), 3)


def reachable_irreps(starts: Iterable[Irrep], depth: int) -> set[Irrep]:
    seen = set(starts)
    frontier = set(seen)
    for _ in range(depth):
        nxt = {child for rep in frontier for child in magnetic_neighbors(rep)} - seen
        seen.update(nxt)
        frontier = nxt
    return seen


@dataclass(frozen=True)
class ParityBasis:
    labels: tuple[Irrep, ...]
    # Unnormalized charge-conjugation parity vectors in the orthonormal
    # character basis.  This keeps every matrix element rational.
    vectors: tuple[Mapping[Irrep, Q], ...]
    gram_diagonal: tuple[Q, ...]


def parity_basis(starts: Iterable[Irrep], parity: int, depth: int) -> ParityBasis:
    if parity not in (-1, 1):
        raise ValueError("parity must be +1 or -1")
    raw = reachable_irreps(starts, depth)
    raw.update((q, p) for p, q in tuple(raw))

    labels: list[Irrep] = []
    vectors: list[Mapping[Irrep, Q]] = []
    gram: list[Q] = []
    for p, q in sorted(raw):
        if p < q:
            continue
        if p == q:
            if parity < 0:
                continue
            labels.append((p, q))
            vectors.append({(p, q): Q(1)})
            gram.append(Q(1))
        else:
            labels.append((p, q))
            vectors.append({(p, q): Q(1), (q, p): Q(parity)})
            gram.append(Q(2))
    return ParityBasis(tuple(labels), tuple(vectors), tuple(gram))


def magnetic_bilinear(left: Mapping[Irrep, Q], right: Mapping[Irrep, Q]) -> Q:
    """Return <left|W|right> for W=-(chi_3+chi_3bar)."""
    total = Q(0)
    for a, ca in left.items():
        for b, cb in right.items():
            total -= ca * cb * magnetic_multiplicity(a, b)
    return total


def matrix_vector(matrix: Sequence[Sequence[Q]], vector: Sequence[Q]) -> list[Q]:
    return [sum((row[j] * vector[j] for j in range(len(vector))), Q(0)) for row in matrix]


def exact_energy_series(
    starts: Iterable[Irrep], parity: int, root: Irrep, order: int = ORDER
) -> tuple[Q, ...]:
    """Intermediate-normalized Rayleigh-Schrödinger series in exact arithmetic."""
    basis = parity_basis(starts, parity, order)
    try:
        root_index = basis.labels.index(root)
    except ValueError as exc:
        raise GateFailure(f"root irrep {root} missing from parity basis") from exc

    size = len(basis.labels)
    energies = [electric_energy(rep) for rep in basis.labels]
    e0 = energies[root_index]

    # B_ij=<b_i|W|b_j>; A=G^-1 B is the coordinate-space operator.
    bilinear = [
        [magnetic_bilinear(basis.vectors[i], basis.vectors[j]) for j in range(size)]
        for i in range(size)
    ]
    operator = [
        [bilinear[i][j] / basis.gram_diagonal[i] for j in range(size)]
        for i in range(size)
    ]

    psi0 = [Q(0)] * size
    psi0[root_index] = Q(1)
    corrections: list[list[Q]] = [psi0]
    coefficients = [e0]

    for n in range(1, order + 1):
        v_previous = matrix_vector(operator, corrections[n - 1])
        en = v_previous[root_index]
        coefficients.append(en)
        if n == order:
            break

        rhs = list(v_previous)
        for j in range(1, n + 1):
            older = corrections[n - j]
            rhs = [rhs[i] - coefficients[j] * older[i] for i in range(size)]

        psi_n = [Q(0)] * size
        for i, energy in enumerate(energies):
            if i == root_index:
                continue
            if energy == e0:
                # Charge conjugation should make the residual in any excluded
                # degenerate partner vanish identically.
                if rhs[i] != 0:
                    raise GateFailure(
                        f"unresolved degeneracy at {basis.labels[i]}: residual={rhs[i]}"
                    )
                continue
            psi_n[i] = rhs[i] / (e0 - energy)
        corrections.append(psi_n)

    return tuple(coefficients)


def one_face_certificate() -> dict[str, tuple[Q, ...]]:
    vacuum = exact_energy_series(((0, 0),), +1, (0, 0))
    axial = exact_energy_series(((1, 0), (0, 1)), -1, (1, 0))
    gap = tuple(axial[i] - vacuum[i] for i in range(ORDER + 1))

    if vacuum != EXPECTED_VACUUM:
        raise GateFailure(f"vacuum series mismatch: {vacuum}")
    if axial != EXPECTED_AXIAL:
        raise GateFailure(f"axial series mismatch: {axial}")
    if gap != EXPECTED_GAP:
        raise GateFailure(f"one-face gap mismatch: {gap}")
    return {"vacuum": vacuum, "axial": axial, "gap": gap}


def layer_coupling_allowed(left: str, right: str) -> bool:
    """One W insertion changes the Krylov/layer distance by at most one."""
    return abs(LAYER_DEPTH[left] - LAYER_DEPTH[right]) <= 1


def closed_layer_paths(insertions: int) -> tuple[tuple[str, ...], ...]:
    """Enumerate P-to-P layer paths with exactly ``insertions`` W factors."""
    if insertions < 0:
        raise ValueError("insertions must be nonnegative")
    paths: list[tuple[str, ...]] = []
    queue: deque[tuple[str, ...]] = deque([("P",)])
    while queue:
        path = queue.popleft()
        used = len(path) - 1
        if used == insertions:
            if path[-1] == "P":
                paths.append(path)
            continue
        for nxt in LAYERS:
            if layer_coupling_allowed(path[-1], nxt):
                queue.append(path + (nxt,))
    return tuple(paths)


def uses_w22(path: Sequence[str]) -> bool:
    return any(left == right == "Q2" for left, right in zip(path, path[1:]))


def center_admissible_patterns(cap: int) -> set[tuple[int, int]]:
    """Nonempty SU(3)-center-admissible (U,Ubar) counts up to ``cap``."""
    return {
        (u_count, bar_count)
        for u_count in range(cap + 1)
        for bar_count in range(cap + 1 - u_count)
        if u_count + bar_count > 0 and (u_count - bar_count) % 3 == 0
    }


def block_occurrence_cap(left: str, right: str) -> int:
    """Maximum local factors in <L_left|W|L_right>: 3+left+right."""
    return 3 + LAYER_DEPTH[left] + LAYER_DEPTH[right]


def order_structure_certificate() -> dict[str, object]:
    o4_paths = closed_layer_paths(4)
    o5_paths = closed_layer_paths(5)
    o4_w22 = tuple(path for path in o4_paths if uses_w22(path))
    o5_w22 = tuple(path for path in o5_paths if uses_w22(path))

    if o4_w22:
        raise GateFailure(f"W22 unexpectedly reachable at O(u^4): {o4_w22}")
    expected_first = ("P", "Q1", "Q2", "Q2", "Q1", "P")
    if o5_w22 != (expected_first,):
        raise GateFailure(f"unexpected first W22 path census: {o5_w22}")

    required_blocks = {
        tuple(sorted((left, right)))
        for path in o4_paths
        for left, right in zip(path, path[1:])
    }
    if ("Q2", "Q2") in required_blocks:
        raise GateFailure("Q2-W-Q2 was admitted into the fourth-order block schedule")
    occurrence_cap = max(block_occurrence_cap(*block) for block in required_blocks)
    if occurrence_cap != 6:
        raise GateFailure(f"unexpected fourth-order local occurrence cap: {occurrence_cap}")
    a6 = center_admissible_patterns(occurrence_cap)
    a7 = center_admissible_patterns(occurrence_cap + 1)
    if a6 != EXPECTED_A6:
        raise GateFailure(f"six-occurrence SU(3) census mismatch: {sorted(a6)}")
    if a7 - a6 != REGRESSION_SIGNATURES:
        raise GateFailure(f"seven-occurrence delta mismatch: {sorted(a7 - a6)}")
    return {
        "o4_paths": o4_paths,
        "o5_w22_paths": o5_w22,
        "required_blocks": tuple(sorted(required_blocks)),
        "occurrence_cap": occurrence_cap,
        "required_patterns": tuple(sorted(a6)),
        "forbidden_o4_signatures": tuple(sorted(REGRESSION_SIGNATURES)),
    }


def notebook_or_python_source(path: Path, raw_bytes: bytes | None = None) -> str:
    if raw_bytes is None:
        raw_bytes = path.read_bytes()
    text = raw_bytes.decode("utf-8")
    if path.suffix.lower() != ".ipynb":
        return text
    payload = json.loads(text)
    chunks: list[str] = []
    for cell in payload.get("cells", []):
        if cell.get("cell_type") == "code":
            source = cell.get("source", [])
            chunks.append("".join(source) if isinstance(source, list) else str(source))
    return "\n\n".join(chunks)


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for chunk in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


class CallCollector(ast.NodeVisitor):
    def __init__(self) -> None:
        self.calls: set[str] = set()
        self.names: set[str] = set()

    def visit_Name(self, node: ast.Name) -> None:
        self.names.add(node.id)

    def visit_Attribute(self, node: ast.Attribute) -> None:
        self.names.add(node.attr)
        self.generic_visit(node)

    def visit_Call(self, node: ast.Call) -> None:
        if isinstance(node.func, ast.Name):
            self.calls.add(node.func.id)
        elif isinstance(node.func, ast.Attribute):
            self.calls.add(node.func.attr)
        self.generic_visit(node)


def function_dependencies(
    tree: ast.Module,
) -> tuple[dict[str, set[str]], dict[str, set[str]], set[str], set[str], set[str]]:
    functions: dict[str, set[str]] = {}
    references: dict[str, set[str]] = {}
    top_level_calls: set[str] = set()
    top_level_names: set[str] = set()
    all_names: set[str] = set()
    for node in tree.body:
        collector = CallCollector()
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            collector.visit(node)
            functions[node.name] = collector.calls
            references[node.name] = collector.names
            all_names.update(collector.names)
        else:
            collector.visit(node)
            top_level_calls.update(collector.calls)
            top_level_names.update(collector.names)
            all_names.update(collector.names)
    return functions, references, top_level_calls, top_level_names, all_names


def shortest_call_path(graph: Mapping[str, set[str]], start: str, goal: str) -> tuple[str, ...] | None:
    queue: deque[tuple[str, ...]] = deque([(start,)])
    seen = {start}
    while queue:
        path = queue.popleft()
        here = path[-1]
        if here == goal:
            return path
        for nxt in graph.get(here, set()):
            if nxt not in seen:
                seen.add(nxt)
                queue.append(path + (nxt,))
    return None


def reachable_functions(graph: Mapping[str, set[str]], start: str) -> set[str]:
    reached: set[str] = set()
    queue = deque([start])
    while queue:
        here = queue.popleft()
        if here in reached:
            continue
        reached.add(here)
        queue.extend(name for name in graph.get(here, set()) if name in graph)
    return reached


def audit_candidate(path: Path) -> dict[str, object]:
    """Conservatively scan for the concrete recorded v10a25 call-chain regression."""
    raw_bytes = path.read_bytes()
    source = notebook_or_python_source(path, raw_bytes)
    parsed_sha256 = hashlib.sha256(raw_bytes).hexdigest()
    try:
        tree = ast.parse(source, filename=str(path))
    except SyntaxError as exc:
        raise GateFailure(f"candidate does not parse: {exc}") from exc

    graph, references, top_calls, top_names, all_names = function_dependencies(tree)
    # Treat references to locally defined functions as dependency edges too.
    # This closes the exact alias hole ``bad = _v23c_build_basis; bad()``.
    dependency_graph = {
        name: set(calls) | (references.get(name, set()) & graph.keys())
        for name, calls in graph.items()
    }
    failures: list[str] = []

    for node in ast.walk(tree):
        if isinstance(node, (ast.Import, ast.ImportFrom)):
            for alias in node.names:
                imported_name = alias.name.rsplit(".", 1)[-1]
                if imported_name in LEGACY_SYMBOLS:
                    failures.append(
                        f"imported legacy symbol is opaque to local audit: {imported_name}"
                    )

    legacy_literals = {
        node.value
        for node in ast.walk(tree)
        if isinstance(node, ast.Constant)
        and isinstance(node.value, str)
        and node.value in LEGACY_SYMBOLS
    }
    if legacy_literals and (top_calls & DYNAMIC_LOOKUP_CALLS):
        failures.append(
            "top-level reflective lookup of legacy symbol(s): "
            + repr(tuple(sorted(legacy_literals)))
        )

    watchdog_tokens = (
        "dump_traceback_later",
        "setitimer",
        "SIGALRM",
        "threading.Timer",
    )
    for token in watchdog_tokens:
        if token in source:
            failures.append(f"asynchronous watchdog token present: {token}")

    # The failed repair called an inherited _v23c_fit_cluster from top level.
    # If its body is absent, the execution path is opaque and cannot be certified.
    if "_v23c_fit_cluster" in top_calls and "_v23c_fit_cluster" not in graph:
        failures.append("top-level call to inherited/opaque _v23c_fit_cluster")
    if "_v23c_fit_cluster" in top_names and "_v23c_fit_cluster" not in top_calls:
        failures.append("top-level alias/reference to _v23c_fit_cluster is not statically callable")

    direct_path = shortest_call_path(dependency_graph, "_v23c_fit_cluster", "_v23c_build_basis")
    if direct_path:
        failures.append("full restricted-basis route reachable: " + " -> ".join(direct_path))

    for target in ("qhaar", "_qcache"):
        path_to_target = shortest_call_path(dependency_graph, "_v23c_fit_cluster", target)
        if path_to_target:
            failures.append("forbidden legacy route reachable: " + " -> ".join(path_to_target))

    for function_name in sorted(reachable_functions(dependency_graph, "_v23c_fit_cluster")):
        dynamic = graph.get(function_name, set()) & DYNAMIC_LOOKUP_CALLS
        if dynamic:
            failures.append(
                f"dynamic lookup/call in reachable function {function_name}: {tuple(sorted(dynamic))}"
            )
        for target in ("qhaar", "_qcache", "_v23c_build_basis"):
            if target in references.get(function_name, set()):
                failures.append(f"{target} referenced from reachable function {function_name}")

    # A literal regression signature in a raised diagnostic is not itself bad;
    # direct calls/references from the legacy fit path are.  The name inventory
    # is reported to make unresolved dynamic dependencies visible.
    called_names = set(top_calls)
    for callees in graph.values():
        called_names.update(callees)
    unresolved = tuple(
        sorted(
            name
            for name in called_names | all_names
            if name.startswith("_v23c_") and name not in graph
        )
    )
    if unresolved:
        failures.append(f"unresolved inherited _v23c dependencies: {unresolved}")

    if failures:
        raise GateFailure("; ".join(failures))
    return {
        "path": str(path),
        "sha256": parsed_sha256,
        "functions": len(graph),
        "top_level_calls": len(top_calls),
        "contains_qhaar_name": "qhaar" in all_names,
        "status": "no recorded static v10a25 regression found; execution proof still required",
    }


def format_series(values: Sequence[Q]) -> str:
    return "[" + ", ".join(str(value) for value in values) + "]"


def run(audit_path: Path | None = None) -> int:
    print("HODGE O(u^4) ROOT-ONLY FIREWALL v1")
    print("=" * 72)

    one_face = one_face_certificate()
    print(f"[PASS] exact vacuum character series : {format_series(one_face['vacuum'])}")
    print(f"[PASS] exact axial character series  : {format_series(one_face['axial'])}")
    print(f"[PASS] exact one-face gap series     : {format_series(one_face['gap'])}")

    structure = order_structure_certificate()
    print(f"[PASS] O(u^4) closed layer paths     : {len(structure['o4_paths'])}")
    print("[PASS] Q2-W-Q2 absent through O(u^4)")
    print(f"[PASS] first Q2-W-Q2 path is O(u^5) : {structure['o5_w22_paths'][0]}")
    print(f"[PASS] required O(u^4) blocks        : {structure['required_blocks']}")
    print(f"[PASS] required local-factor cap     : {structure['occurrence_cap']}")
    print(f"[PASS] complete SU(3) pattern census : {structure['required_patterns']}")
    print("[PASS] (2,5)/(5,2) are exactly the cap-7 delta and O(u^4) regression witnesses")

    if audit_path is not None:
        report = audit_candidate(audit_path)
        print(f"[SCAN] no known static regression    : {report['path']}")
        print(f"[SCAN] parsed candidate SHA-256       : {report['sha256']}")
        print("[NOTE] scan is non-authoritative; dynamic root-path/W22 sentinels are mandatory")

    print("=" * 72)
    print("[ROOT-ONLY PASS] no W22/full-Q2 matrix is required or exercised")
    print(f"firewall SHA-256: {sha256_file(Path(__file__).resolve())}")
    return 0


def parse_args(argv: Sequence[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--audit",
        type=Path,
        help="also audit a Python or .ipynb candidate for the recorded v10a25 route",
    )
    return parser.parse_args(argv)


def main(argv: Sequence[str] | None = None) -> int:
    args = parse_args(sys.argv[1:] if argv is None else argv)
    try:
        return run(args.audit)
    except (GateFailure, OSError, ValueError, json.JSONDecodeError) as exc:
        print(f"[FAIL] {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
