"""Render the human route map from the statement and Lean dependency records."""

from __future__ import annotations

import argparse
from pathlib import Path

from workhouse import derivation_statements as D
from workhouse import lean_dependencies as L

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "docs/derivation_formalization.md"


def render() -> str:
    data = D._checked()
    kernel = L.load()
    statements = [r for d in data["documents"] for r in d["statements"]]
    fully = sum(bool(r["lean"]) for r in statements)
    partial = sum(bool(r.get("lean_support")) and not r["lean"] for r in statements)
    linked = {n for r in statements for n in r["lean"]}
    linked.update(s["name"] for r in statements for s in r.get("lean_support", []))
    lines = [
        "# Derivation proof map",
        "",
        "Generated by `python scripts/render_derivation_coverage.py`; edit the source ledgers.",
        "",
        f"The map covers **{len(data['documents'])} derivation documents and "
        f"{len(statements)} statement groups**. {fully} groups have whole-statement Lean "
        f"links; {partial} more have explicitly scoped formal ingredients. "
        f"{len(statements) - fully - partial} have no direct Lean link yet. "
        f"{len(linked)} distinct Lean declarations are attached to these statements.",
        "",
        "Coverage is not a percentage of mathematics proved: one group can contain several "
        "equations or a substantial analytic construction. An established analytic result "
        "keeps its mathematical status even when its complete formalization remains open.",
        "",
        "## Read a proof and its dependencies",
        "",
        "1. Use the statement ID in [the source-pinned inventory]"
        "(../ledger/derivation_statements.yaml). Each record has the exact source SHA-256, "
        "section/line locator, hypotheses, source dependencies and remaining formalization.",
        "2. `workhouse why DERIV:WILSON_SC17_THERMODYNAMIC_LIMIT:IF4_CLOSABLE` shows the "
        "source claim and its scoped Lean support. `formalizes` means the whole named "
        "statement; `supported_by` means the stated ingredient only.",
        "3. `workhouse why LEAN:closed_extension_of_integration_by_parts` shows the "
        "compiled declaration and its actual project proof dependencies. "
        "The [kernel export](../ledger/lean_dependencies.json) also includes every directly "
        "used mathlib constant and transitive axiom. Local definitions are traversed until "
        "the next registered theorem; mathematical source dependencies are curated separately.",
        "",
        f"The kernel export currently covers {len(kernel['theorems'])} registered theorems. "
        "It is rejected if a Lean source, import root or toolchain pin changes. Lean "
        "fingerprints normalize line endings only (`utf8-lf`); derivation hashes preserve "
        "the original bytes. Dependency extraction does not prove that a source theorem "
        "has been faithfully encoded; the precise scoped mapping records that review.",
        "",
        "## Current analytic modules",
        "",
        "| Module | Checked mechanism |",
        "| --- | --- |",
        "| [ResolventLocalization](../lean/Workhouse/ResolventLocalization.lean) | Infinite "
        "Neumann inverse, cubic operator remainder, signed resolvent pairing, Schur minimum "
        "and infinite lattice localization sums |",
        "| [GroundStateAssembly](../lean/Workhouse/GroundStateAssembly.lean) | Actual "
        "probability-measure comparison, noncommuting projection assembly, physical "
        "form-domain transport and covariance control |",
        "| [ThermodynamicLimit](../lean/Workhouse/ThermodynamicLimit.lean) | Weak law and "
        "uniform-score passage, integration by parts, unbounded-operator closure, form-core "
        "inequalities and spectral interval mass |",
        "| [SpectralReconstruction](../lean/Workhouse/SpectralReconstruction.lean) | Positive "
        "spectral measure, exponential decay, low-energy support exclusion and dense-family "
        "projection extension |",
        "| [PlateauObstruction](../lean/Workhouse/PlateauObstruction.lean) | Exact "
        "exponential minimum and a positive slow-mode witness for every nonzero plateau |",
        "",
        "These mechanisms supply reusable formal steps. Their application to the actual "
        "Wilson objects still requires the recorded cylinder, domain, projection, "
        "semigroup and model-identification hypotheses. In particular, constructing the "
        "full closed Dirichlet generator and physical-time stochastic limit, proving the "
        "complete interacting source/frame identification, and transporting the fixed-spacing "
        "construction to the spatial continuum remain separate obligations.",
        "",
        "## Document coverage",
        "",
        "| Derivation | Groups | Whole statement | Scoped ingredients only | No Lean link |",
        "| --- | ---: | ---: | ---: | ---: |",
    ]
    for doc in data["documents"]:
        rows = doc["statements"]
        whole = sum(bool(r["lean"]) for r in rows)
        support = sum(bool(r.get("lean_support")) and not r["lean"] for r in rows)
        title = Path(doc["path"]).stem
        lines.append(
            f"| [{title}](../{doc['path']}) | {len(rows)} | {whole} | "
            f"{support} | {len(rows) - whole - support} |"
        )
    lines += [
        "",
        "## Remaining work by precise statement",
        "",
        "The full formal declarations carry their own explicit hypotheses. The table below "
        "retains each source-level successor obligation; adding a supporting lemma alone "
        "does not discharge it. Use the stable ID to traverse its prerequisites in the graph.",
        "",
    ]
    for doc in data["documents"]:
        lines += [
            f"### {Path(doc['path']).stem}",
            "",
            f"[Source](../{doc['path']}) — `{doc['sha256']}`",
            "",
            "| Statement ID | Coverage | Remaining formalization |",
            "| --- | --- | --- |",
        ]
        for row in doc["statements"]:
            scope = (
                "whole statement"
                if row["lean"]
                else "scoped ingredients"
                if row.get("lean_support")
                else "not yet linked"
            )
            remaining = row["remaining"].replace("|", "\\|").replace("\n", " ")
            lines.append(
                f"| `{row['id']}` | {scope} | {remaining or 'No remaining step recorded.'} |"
            )
        lines.append("")
    lines += [
        "## Updating this map",
        "",
        "```powershell",
        "uv run --no-sync python scripts/export_lean_dependencies.py",
        "uv run --no-sync python scripts/render_derivation_coverage.py",
        "uv run --no-sync workhouse index -w",
        "uv run --no-sync workhouse frontier --write",
        "uv run --no-sync workhouse certified --write",
        "uv run --no-sync workhouse atlas",
        "```",
        "",
        "Register every new theorem, including helpers. Review changed source hashes "
        "against preserved originals before updating them. Keep mathematical status, "
        "formal coverage and repository landing status separate.",
        "",
    ]
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    content = render()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != content:
            raise SystemExit("stale derivation proof map; rerun this script without --check")
    else:
        OUTPUT.write_text(content, encoding="utf-8")
        print(OUTPUT)


if __name__ == "__main__":
    main()
