#!/usr/bin/env python3
"""Regenerate ledger/governing_register.yaml from the governing document's §14.

The item text is copied verbatim, never paraphrased: `tests/test_ledger.py`
re-extracts §14 and compares, so a drifted transcription fails the build. Only
the crosswalk below is authored by hand, and it is deliberately sparse — an
entry appears only where the register item and the C-id state the *same* claim,
not merely a related one. Run this after a corpus version bump, then extend
CROSSWALK for whatever the new version added.

    python scripts/transcribe_register.py
"""

from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DOCUMENT = ROOT / "theory" / "MASTER_THEORY_UNIFIED_2026-08-20_v4_3.md"
OUT = ROOT / "ledger" / "governing_register.yaml"

#: id -> (contradiction ids stating the same claim, gap ids the item bears on, note)
CROSSWALK: dict[str, tuple[list[str], list[str], str]] = {
    "R1": (["C4"], [], "Same claim: the Y line is a label erratum, so no 4**n rescaling."),
    "R2": (
        [],
        [],
        "Refines C4 from the SU(3) coordinate u = beta_lat/6 to all-rank u = beta_N/(2N).",
    ),
    "R3": (
        [],
        [],
        "Not in the §8 register; MASTER_THEORY.md §4.3 states the opposite and is wrong.",
    ),
    "R4": (
        ["C1"],
        [],
        "Same claim: q_band^(4) and m_Gamma^(4) are differently anchored coordinates.",
    ),
    "R5": (["C2"], ["G3"], "Same claim, and the one genuinely open contradiction."),
    "R6": (
        ["C22"],
        [],
        "Same claim: the shift was target-derived, so the equality is bookkeeping.",
    ),
    "R7": ([], ["G14"], "The tier collapse itself; G14 is the open question of its mechanism."),
    "R8": (
        ["C12"],
        [],
        "Same claim: radial directional second derivatives, Hessian only if beta = 2*alpha.",
    ),
    "R9": (
        [],
        [],
        "Positive S_r requires (-1)**(r+1). Distinct from the sigma sign convention in R14.",
    ),
    "R10": (
        ["C6"],
        [],
        "Same claim: the static circuit/mobility promotion is not a universal equality.",
    ),
    "R11": ([], [], "The weak-well theorem's remainder order; see §10.3."),
    "R12": (
        ["C21"],
        [],
        "Same claim: the stored amplitude is not a normalized overlap probability.",
    ),
    "R13": (["C9"], [], "Same claim: a flat-branch eigenvalue identity, not scalarity."),
    "R14": (
        ["C5"],
        ["G7"],
        "C5's -61/408 is the n = 3 instance of sigma_n^phys = (-1)**n * sigma_n^raw.",
    ),
    "R15": ([], ["G9"], "Scopes the exact m_6 to the q_band^(4) branch."),
    "R16": ([], [], "About upstream registry files that are not in this repository."),
    "R17": ([], [], "Declares the old incident-step reduction false; see §12.3."),
    "R18": ([], ["G1"], "A missing analysis JSON; the complete ZIP is the reproducible authority."),
    "R19": (
        [],
        ["G11"],
        "Downgrades Lemma A pending intervalization; G11 tracks the interval rigor.",
    ),
    "R20": ([], ["G4"], "Bundle provenance for h_4^side."),
    "R21": (
        ["C8"],
        ["G4"],
        "Same subject as C8 and its resolution: the physical manifold is cap-only.",
    ),
    "R22": (
        [],
        ["G10"],
        "The direct fifth-order pentagonal fraction is transcript-backed, not a theorem.",
    ),
    "R23": (
        ["C3"],
        [],
        "Same claim: a finite-order computational result is not the promoted theorem.",
    ),
}

HEADER = """\
# Governing contradiction and errata register — MASTER_THEORY_UNIFIED v4.3 §14.
#
# GENERATED by scripts/transcribe_register.py. `text` is verbatim; do not edit
# it by hand. tests/test_ledger.py re-extracts §14 and compares.
#
# This is the AUTHORITY. contradictions.yaml transcribes the older
# MASTER_THEORY.md §8 register (C1-C22), which has its own numbering and is not
# governing. Where the two disagree, this file controls. `contradictions` below
# is deliberately sparse: an id appears only where the two state the same claim.
schema: governing-register/v1
source: theory/MASTER_THEORY_UNIFIED_2026-08-20_v4_3.md §14
supersedes: theory/superseded/MASTER_THEORY_UNIFIED_2026-08-20_v3.md §14
"""


def items(document: Path) -> list[tuple[str, str]]:
    section = re.search(
        r"^## 14\. Governing contradiction and errata register\n(.*?)^---$",
        document.read_text(),
        re.MULTILINE | re.DOTALL,
    )
    if section is None:
        raise SystemExit(f"{document} has no §14 register")
    out = []
    for raw in re.split(r"^\d+\. ", section.group(1), flags=re.MULTILINE)[1:]:
        text = " ".join(raw.split())
        title = re.match(r"\*\*(.+?)\.\*\*", text)
        out.append((title.group(1) if title else "", text))
    return out


def render(entries: list[tuple[str, str]]) -> str:
    def block(value: str, indent: str) -> str:
        # Literal block scalar: verbatim text with no quoting rules to get wrong.
        return "|-\n" + "\n".join(indent + line for line in [value])

    lines = [HEADER, "items:"]
    for n, (title, text) in enumerate(entries, 1):
        rid = f"R{n}"
        contradictions, gaps, note = CROSSWALK.get(rid, ([], [], ""))
        lines.append(f"  - id: {rid}")
        lines.append(f"    title: {title}")
        lines.append(f"    text: {block(text, '      ')}")
        lines.append(f"    contradictions: [{', '.join(contradictions)}]")
        lines.append(f"    gaps: [{', '.join(gaps)}]")
        if note:
            lines.append(f"    note: {block(note, '      ')}")
        lines.append("")
    return "\n".join(lines)


if __name__ == "__main__":
    entries = items(DOCUMENT)
    missing = sorted(set(f"R{i}" for i in range(1, len(entries) + 1)) - set(CROSSWALK))
    if missing:
        raise SystemExit(f"CROSSWALK has no entry for {missing}; add one (empty lists are fine)")
    OUT.write_text(render(entries))
    print(f"{OUT}: {len(entries)} items")
