#!/usr/bin/env python3
"""Flatten a driver and its \\input tree into one self-contained .tex file.

The edition is modular on purpose --- two drivers share one set of section
files so the monograph and the extractable band paper cannot drift.  That
is right for maintenance and wrong for handing someone a single file, so
this produces the single file on demand rather than as a second source of
truth.

The bibliography is inlined from the .bbl when one is present, so the
result needs no .bib and no BibTeX pass:

    tectonic paper/master/workhouse_master.tex        # produces the .bbl
    python  paper/master/assemble_selfcontained.py

Output goes beside the drivers as <driver>_selfcontained.tex.

Run from the repository root.
"""

from __future__ import annotations

import pathlib
import re
import sys

HERE = pathlib.Path(__file__).resolve().parent

# \input{name} on a line of its own, optionally indented.  The edition never
# uses \include, and never puts two \input calls on one line.
INPUT = re.compile(r"^[ \t]*\\input\{([^}]+)\}[ \t]*$")
BIB = re.compile(r"^[ \t]*\\bibliography\{([^}]+)\}[ \t]*$")
BIBSTYLE = re.compile(r"^[ \t]*\\bibliographystyle\{[^}]*\}[ \t]*$")

DRIVERS = ["workhouse_master", "workhouse_band_paper"]


def flatten(name: str, seen: set[str], depth: int = 0) -> list[str]:
    """Return the lines of `name`, with its \\input tree spliced in."""
    path = HERE / (name if name.endswith(".tex") else name + ".tex")
    if not path.exists():
        raise SystemExit(f"missing input: {path}")
    key = path.name
    if key in seen:
        raise SystemExit(f"input cycle at {key}")
    seen.add(key)

    out: list[str] = []
    for line in path.read_text(encoding="utf-8").splitlines():
        m = INPUT.match(line)
        if m:
            child = m.group(1)
            out.append(f"% ---- begin {child}.tex " + "-" * max(0, 52 - len(child)))
            out.extend(flatten(child, seen, depth + 1))
            out.append(f"% ---- end {child}.tex " + "-" * max(0, 54 - len(child)))
            continue
        out.append(line)
    seen.discard(key)
    return out


def inline_bibliography(lines: list[str], driver: str) -> list[str]:
    """Replace \\bibliography{...} with the compiled .bbl, if there is one.

    Without a .bbl the line is left alone: a caller who has not built yet
    should get a file that still works with BibTeX rather than one whose
    references have silently vanished.
    """
    bbl = HERE / f"{driver}.bbl"
    if not bbl.exists():
        print(f"  note: {bbl.name} absent, leaving \\bibliography in place")
        return lines

    body = bbl.read_text(encoding="utf-8").rstrip().splitlines()
    out: list[str] = []
    for line in lines:
        if BIBSTYLE.match(line):
            continue
        if BIB.match(line):
            out.append("% ---- begin inlined bibliography " + "-" * 34)
            out.extend(body)
            out.append("% ---- end inlined bibliography " + "-" * 36)
            continue
        out.append(line)
    return out


BANNER = """\
% =====================================================================
% {title}
%
% SELF-CONTAINED EDITION.  Generated by paper/master/assemble_selfcontained.py
% from the modular sources in paper/master/.  Do not edit this file: edit
% the section files and re-assemble, or the two will disagree.
%
% Needs no other file.  Build with:
%     tectonic {driver}_selfcontained.tex
% or  pdflatex {driver}_selfcontained.tex   (twice, for cross-references)
%
% Standard packages only, no shell escape, no images, no .bib.
% =====================================================================
"""


def main() -> int:
    targets = sys.argv[1:] or DRIVERS
    for driver in targets:
        driver = driver.removesuffix(".tex")
        lines = flatten(driver, set())
        lines = inline_bibliography(lines, driver)
        banner = BANNER.format(
            title=(
                "THE WORKHOUSE PROGRAM --- master edition"
                if "master" in driver
                else "EXACT SU(N) FLUX-BAND SPECTRA --- standalone"
            ),
            driver=driver,
        )
        dest = HERE / f"{driver}_selfcontained.tex"
        dest.write_text(banner + "\n".join(lines) + "\n", encoding="utf-8")
        kb = dest.stat().st_size / 1024
        print(f"wrote {dest.name}: {len(lines)} lines, {kb:.0f} KB")
    return 0


if __name__ == "__main__":
    sys.exit(main())
