#!/usr/bin/env python3
"""Generate the source-provenance apparatus: where every derivation comes from.

Companion to generate_apparatus.py, which covers claims, routes and the
evidence map.  This one answers the different question an agent asks:
*given a statement, what do I read, and how do I know I am reading the
bytes it was derived from?*

Seven artefacts, all derived:

  gen_concordance.tex   every DERIV statement -> document, SHA-256, locator
  gen_lean.tex          every Lean theorem -> module:line, what it covers
  gen_library.tex       the curated published library, by tier and category
  gen_extraction.tex    the page-level extraction index over local PDFs
  gen_symbols.tex       the join keys: canonical name, spellings, values
  gen_documents.tex     document aliases and their standing
  gen_srcmacros.tex     counts, as \\newcommand

Run from the repository root:

    python paper/master/generate_sources.py
"""

from __future__ import annotations

import collections
import csv
import json
import pathlib
import re
import sys

import yaml

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
from generate_apparatus import first_sentences, tex  # noqa: E402

ROOT = pathlib.Path(__file__).resolve().parents[2]
OUT = ROOT / "paper" / "master"


def load(name: str):
    with open(ROOT / name, encoding="utf-8") as fh:
        return yaml.safe_load(fh)


def short_sha(s: object, n: int = 12) -> str:
    return str(s)[:n] if s else ""


def breakable(s: object) -> str:
    """A path that TeX may wrap.

    \\nolinkurl typesets a path as one unbreakable box, which overfills the
    line for any repository path of realistic depth.  Inside a narrow table
    column the wrapping matters more than the copy-paste fidelity that
    \\nolinkurl protects, so break after each separator instead.
    """
    return tex(s).replace("/", "/\\allowbreak{}").replace("-", "-\\allowbreak{}")


def header(*lines: str) -> list[str]:
    return ["% Generated by paper/master/generate_sources.py.  Do not edit.", *lines]


def small(s: object) -> str:
    """Wrap a cell in a size group.  These tables are dense by design."""
    return "{\\scriptsize " + str(s) + "}"


def mono(s: object) -> str:
    return "{\\scriptsize\\ttfamily " + str(s) + "}"


def row(*cells: str) -> str:
    """One longtable row: cells joined by & and terminated."""
    return " & ".join(cells) + r" \\"


# --------------------------------------------------------------------------
# 1.  The derivation concordance
# --------------------------------------------------------------------------


def make_concordance(docs) -> str:
    """One subsection per source document, one row per statement in it.

    The locator is the part an agent actually needs: it names the heading
    and line range inside the document, so a statement can be found without
    reading the whole file.
    """
    out = header()
    total = sum(len(d.get("statements") or []) for d in docs)
    out.append(
        f"\\noindent The concordance below covers all {total} registered "
        f"derivation statements across {len(docs)} source documents. Each "
        f"document carries the SHA-256 of the bytes its statements were read "
        f"from; if the file has changed, the digest has changed and the "
        f"statements must be re-located rather than assumed.\\par\\medskip"
    )

    for d in sorted(docs, key=lambda x: x["id"]):
        cid = tex(d["id"])
        # The contents line gets the identifier without its CITE: prefix:
        # the full form is wider than the page in a table of contents.
        short = tex(str(d["id"]).split(":", 1)[-1])
        out.append(f"\\subsection*{{{cid}}}")
        out.append(f"\\addcontentsline{{toc}}{{subsection}}{{{short}}}")
        out.append(
            f"\\noindent\\srcpath{{{tex(d.get('path'))}}}\\\\\n"
            f"{{\\footnotesize SHA-256 "
            f"\\texttt{{{short_sha(d.get('sha256'), 16)}}}\\ldots}}"
            f"\\par\\smallskip"
        )
        stmts = d.get("statements") or []
        if not stmts:
            out.append("")
            continue
        out.append("\\begin{longtable}{@{}p{0.30\\linewidth} p{0.30\\linewidth} l l@{}}")
        out.append("\\toprule Statement & Locator & Status & Formal \\\\ \\midrule")
        out.append("\\endfirsthead")
        out.append("\\toprule Statement & Locator & Status & Formal \\\\ \\midrule \\endhead")
        out.append("\\bottomrule\\endfoot")
        for s in stmts:
            sid = str(s["id"]).split(":")[-1]
            # Whole-statement Lean coverage and partial support are different
            # facts and the table keeps them apart.
            if s.get("lean"):
                formal = "full"
            elif s.get("lean_support"):
                formal = "partial"
            else:
                formal = "---"
            out.append(
                row(
                    mono(tex(sid)),
                    small(tex(s.get("locator"))),
                    small(tex(s.get("status"))),
                    small(formal),
                )
            )
        out.append("\\end{longtable}")
        out.append("")
    return "\n".join(out)


def make_open_statements(docs) -> str:
    """The statements that are open or conditional, with what is missing.

    This is the working list: every place the corpus itself records that an
    argument does not close, together with the sentence saying why.
    """
    rows = []
    for d in docs:
        for s in d.get("statements") or []:
            if s.get("status") in ("open", "conditional", "disputed"):
                rows.append((d, s))
    order = {"open": 0, "disputed": 1, "conditional": 2}
    rows.sort(key=lambda r: (order.get(r[1].get("status"), 9), r[1]["id"]))

    out = header()
    out.append(
        f"\\noindent {len(rows)} of the registered derivation statements are "
        f"not recorded as proven. Each is listed with the document it lives "
        f"in, its locator, and the corpus's own sentence on what remains. "
        f"These are the statements an agent can act on directly."
        f"\\par\\medskip"
    )
    # Ledger statements carry inline formulae written for a terminal, with
    # no break points TeX can use; loosen the tolerance rather than reflow
    # mathematics that must be quoted exactly.
    out.append("\\begingroup\\sloppy")
    for d, s in rows:
        sid = str(s["id"])
        out.append(
            f"\\noindent\\textbf{{\\texttt{{\\small {tex(sid)}}}}} "
            f"\\hfill {{\\footnotesize {tex(s.get('status'))}}}\\par"
        )
        out.append(f"{{\\small {first_sentences(s.get('statement'), 3)}}}\\par")
        out.append(
            f"{{\\footnotesize \\srcpath{{{tex(d.get('path'))}}} --- {tex(s.get('locator'))}}}\\par"
        )
        if s.get("hypotheses"):
            hyp = "; ".join(tex(h) for h in s["hypotheses"][:4])
            out.append(f"{{\\footnotesize \\textit{{Hypotheses.}} {hyp}}}\\par")
        if s.get("remaining"):
            out.append(
                f"{{\\footnotesize \\textit{{Remaining.}} "
                f"{first_sentences(s['remaining'], 2)}}}\\par"
            )
        out.append("\\smallskip")
    out.append("\\endgroup")
    return "\n".join(out)


# --------------------------------------------------------------------------
# 2.  The Lean tree
# --------------------------------------------------------------------------


def lean_locations() -> dict:
    """Map theorem name -> "module:line", read from the Lean sources.

    The dependency export records qualified names but not positions, and
    positions are what a reader needs, so they are recovered here from the
    files themselves rather than transcribed.
    """
    loc = {}
    pat = re.compile(
        r"^\s*(?:@\[[^\]]*\]\s*)?(?:private\s+|protected\s+)?"
        r"(?:theorem|lemma)\s+([A-Za-z_][A-Za-z0-9_'.]*)"
    )
    for f in sorted((ROOT / "lean").rglob("*.lean")):
        try:
            lines = f.read_text(encoding="utf-8").splitlines()
        except OSError:
            continue
        rel = f.relative_to(ROOT).as_posix()
        for i, line in enumerate(lines, 1):
            m = pat.match(line)
            if m:
                loc.setdefault(m.group(1), f"{rel}:{i}")
    return loc


def make_lean(theorems, locations) -> str:
    by_module = collections.defaultdict(list)
    for t in theorems:
        where = locations.get(t["name"], "")
        module = where.split(":")[0].split("/")[-1] if where else "(unlocated)"
        by_module[module].append((t, where))

    total = len(theorems)
    promotes = sum(1 for t in theorems if t.get("promotes"))
    formalizes = sum(1 for t in theorems if t.get("formalizes"))
    located = sum(1 for t in theorems if locations.get(t["name"]))

    out = header()
    out.append(
        f"\\noindent {total} registered theorems across {len(by_module)} "
        f"modules. \\emph{{Promotes}} means the theorem proves an entire "
        f"named check and so carries its verification tier; "
        f"\\emph{{formalizes}} means it is linked to a catalogue record. "
        f"Only {promotes} of {total} carry a \\texttt{{promotes}} link, and "
        f"reading the difference as a defect would be a mistake: most "
        f"theorems are ingredients, and the registry keeps ingredient and "
        f"whole-statement coverage apart on purpose.\\par\\medskip"
    )
    for module in sorted(by_module):
        out.append(f"\\subsection*{{{tex(module)}}}")
        out.append(f"\\addcontentsline{{toc}}{{subsection}}{{{tex(module)}}}")
        out.append("\\begin{longtable}{@{}p{0.32\\linewidth} l p{0.44\\linewidth}@{}}")
        out.append("\\toprule Theorem & Line & Formalizes / promotes \\\\ \\midrule")
        out.append("\\endfirsthead")
        out.append("\\toprule Theorem & Line & Formalizes / promotes \\\\ \\midrule \\endhead")
        out.append("\\bottomrule\\endfoot")
        for t, where in sorted(by_module[module], key=lambda x: x[0]["name"]):
            line = where.split(":")[-1] if where else ""
            # Escape first, then add markup: running tex() over the markup
            # turns \textbf into literal backslash-t-e-x-t-b-f in the PDF.
            links = [tex(x) for x in (t.get("formalizes") or [])]
            links += [
                "\\textbf{promotes} " + tex(p) for p in (t.get("promotes") or [])
            ]
            out.append(
                row(
                    mono(tex(t["name"])),
                    small(line),
                    small("; ".join(links) if links else "---"),
                )
            )
        out.append("\\end{longtable}")
        out.append("")
    out.append(f"% located {located} of {total}; formalizes {formalizes}")
    return "\n".join(out)


# --------------------------------------------------------------------------
# 3.  The published library
# --------------------------------------------------------------------------


def read_manifest(rel: str):
    p = ROOT / rel
    if not p.exists():
        return []
    with open(p, encoding="utf-8-sig", newline="") as fh:
        return list(csv.DictReader(fh))


CATEGORY_NAME = {
    "hamiltonian_quantum": "Hamiltonian and quantum-simulation formulations",
    "rigorous_lgt": "Rigorous lattice Yang--Mills",
    "spectrum": "Glueball spectrum and continuum limits",
    "effective_hamiltonian": "Effective Hamiltonians and strong coupling",
    "weingarten": "Weingarten and Haar integration",
    "flat_bands": "Flat bands and compact localized states",
    "flux_strings": "Flux tubes, strings and torelons",
    "strong_coupling": "Strong-coupling expansions",
    "spectral_methods": "Spectral extraction and operator overlap",
}


def make_library(v1, v2) -> str:
    rows = [dict(r, volume="1") for r in v1] + [dict(r, volume="2") for r in v2]
    by_cat = collections.defaultdict(list)
    for r in rows:
        by_cat[r.get("category", "other")].append(r)

    out = header()
    out.append(
        f"\\noindent {len(rows)} acquired papers, all with local full text, "
        f"grouped by the library's own categories. \\emph{{Connection}} is "
        f"the curated one-line statement of what the paper bears on in this "
        f"program; it is a reading note, not an evidence edge. The evidence "
        f"edges are the separate, smaller, verified set in "
        f"\\S\\ref{{sec:external}}. A paper here has been \\emph{{obtained}}, "
        f"which is not the same as \\emph{{read against a claim}}."
        f"\\par\\medskip"
    )
    for cat in sorted(by_cat, key=lambda c: -len(by_cat[c])):
        name = CATEGORY_NAME.get(cat, cat.replace("_", " ").title())
        out.append(f"\\subsection*{{{tex(name)}}}")
        out.append(f"\\addcontentsline{{toc}}{{subsection}}{{{tex(name)}}}")
        out.append("\\begin{longtable}{@{}l p{0.40\\linewidth} l p{0.28\\linewidth}@{}}")
        out.append("\\toprule Year & Title & arXiv & Connection \\\\ \\midrule")
        out.append("\\endfirsthead")
        out.append("\\toprule Year & Title & arXiv & Connection \\\\ \\midrule \\endhead")
        out.append("\\bottomrule\\endfoot")

        def by_year(x):
            return (-int(x.get("year") or 0), x.get("title", ""))

        for r in sorted(by_cat[cat], key=by_year):
            out.append(
                row(
                    tex(r.get("year")),
                    small(tex(r.get("title"))),
                    small("\\texttt{" + tex(r.get("arxiv_id")) + "}"),
                    small(tex(r.get("workhouse_connection"))),
                )
            )
        out.append("\\end{longtable}")
        out.append("")
    return "\n".join(out)


# --------------------------------------------------------------------------
# 4.  The page-level extraction index
# --------------------------------------------------------------------------


def make_extraction() -> tuple[str, dict]:
    path = ROOT / "literature/yangmills/extraction/pages.jsonl"
    stats = {"pages": 0, "papers": 0, "topics": 0, "labelled": 0}
    if not path.exists():
        return "% extraction index absent\n", stats

    per_paper = collections.defaultdict(
        lambda: {"pages": 0, "topics": collections.Counter(), "labels": 0}
    )
    topics = collections.Counter()
    for line in path.open(encoding="utf-8"):
        try:
            d = json.loads(line)
        except json.JSONDecodeError:
            continue
        pid = d.get("paper_id", "?")
        rec = per_paper[pid]
        rec["pages"] += 1
        stats["pages"] += 1
        for t, hits in (d.get("topic_line_hits") or {}).items():
            rec["topics"][t] += len(hits)
            topics[t] += len(hits)
        if d.get("candidate_labels"):
            rec["labels"] += 1
            stats["labelled"] += 1
    stats["papers"] = len(per_paper)
    stats["topics"] = len(topics)

    out = header()
    out.append(
        f"\\noindent {stats['pages']} extracted pages across "
        f"{stats['papers']} works, indexed by topic and line. A row says how "
        f"many pages of that work are searchable and which topics occur in "
        f"it; the index records \\emph{{locators}}, not text, so the reading "
        f"copy under \\srcpath{{literature/inbox/<ID>/extracted/}} is where "
        f"the words are. A hit may be a citation or an extraction error: the "
        f"index is a search aid and certifies nothing.\\par\\medskip"
    )
    out.append("\\begin{longtable}{@{}l r r p{0.46\\linewidth}@{}}")
    out.append("\\toprule Work & Pages & Labelled & Topics present \\\\ \\midrule")
    out.append("\\endfirsthead")
    out.append("\\toprule Work & Pages & Labelled & Topics present \\\\ \\midrule \\endhead")
    out.append("\\bottomrule\\endfoot")
    for pid in sorted(per_paper, key=lambda p: -per_paper[p]["pages"]):
        rec = per_paper[pid]
        tops = ", ".join(f"{tex(t)} ({n})" for t, n in rec["topics"].most_common(6))
        out.append(
            row(
                mono(tex(pid)),
                str(rec["pages"]),
                str(rec["labels"]),
                small(tops or "---"),
            )
        )
    out.append("\\end{longtable}")
    out.append("")
    out.append(
        "\\noindent Searchable topics, with total line hits: {}.\\par".format(
            ", ".join(f"\\texttt{{{tex(t)}}} ({n})" for t, n in topics.most_common())
        )
    )
    return "\n".join(out), stats


# --------------------------------------------------------------------------
# 5.  Symbols: the join keys
# --------------------------------------------------------------------------


def make_symbols(symbols) -> str:
    out = header()
    out.append(
        "\\noindent The join keys of this corpus are exact values and "
        "spellings, not concepts: no natural-language query retrieves "
        "$109151/249696$. The registry below is what makes a value findable "
        "across a document written in one notation, code written in another, "
        "and a claim recorded in a third.\\par\\medskip"
    )
    for s in sorted(symbols, key=lambda x: x["id"]):
        out.append(
            "\\noindent\\textbf{{\\texttt{{{}}}}}".format(tex(s.get("canonical") or s["id"]))
        )
        if s.get("values"):
            out.append(
                " \\hfill {{\\footnotesize values: {}}}".format(
                    ", ".join(f"\\texttt{{{tex(v)}}}" for v in s["values"][:6])
                )
            )
        out.append("\\par")
        out.append("{{\\small {}}}\\par".format(first_sentences(s.get("meaning"), 2)))
        bits = []
        if s.get("corpus_spellings"):
            bits.append(
                "corpus spellings: "
                + ", ".join(f"\\texttt{{{tex(x)}}}" for x in s["corpus_spellings"][:6])
            )
        if s.get("code_names"):
            bits.append(
                "in code: " + ", ".join(f"\\texttt{{{tex(x)}}}" for x in s["code_names"][:6])
            )
        if s.get("claims"):
            bits.append("claims: " + ", ".join(f"\\texttt{{{tex(x)}}}" for x in s["claims"][:8]))
        if bits:
            out.append("{{\\footnotesize {}}}\\par".format(" \\quad ".join(bits)))
        out.append("\\smallskip")
    return "\n".join(out)


# --------------------------------------------------------------------------
# 6.  Document aliases and their standing
# --------------------------------------------------------------------------


def make_documents(aliases) -> str:
    by_standing = collections.defaultdict(list)
    for a in aliases:
        by_standing[a.get("standing", "unrecorded")].append(a)

    out = header()
    out.append(
        f"\\noindent {len(aliases)} source documents carry a registered alias "
        f"and a \\emph{{standing}}. Standing is the single most important "
        f"field for an agent reading the archive: it says whether a document "
        f"is current, superseded, or preserved only as evidence of a stage. "
        f"A superseded document is not deleted and reads exactly like a "
        f"current one.\\par\\medskip"
    )
    for standing in sorted(by_standing, key=lambda s: -len(by_standing[s])):
        group = by_standing[standing]
        out.append(f"\\subsection*{{Standing: {tex(standing)} ({len(group)})}}")
        out.append(f"\\addcontentsline{{toc}}{{subsection}}{{Standing: {tex(standing)}}}")
        # Absolute column widths, not fractions of \linewidth.  Aliases and
        # repository paths are both long, so neither column can be left to
        # size itself; and a fraction of \linewidth is resolved late enough
        # inside longtable that the surrounding context can change it.
        # 2.0in + 4.2in + separation fits the 6.5in text block.
        out.append("\\begin{longtable}{@{}p{2.0in} p{4.2in}@{}}")
        out.append("\\toprule Alias & Path \\\\ \\midrule")
        out.append("\\endfirsthead")
        out.append("\\toprule Alias & Path \\\\ \\midrule \\endhead")
        out.append("\\bottomrule\\endfoot")
        for a in sorted(group, key=lambda x: str(x.get("alias") or "")):
            out.append(
                "{{\\scriptsize\\ttfamily {}}} & {{\\scriptsize\\ttfamily {}}} \\\\".format(
                    breakable(a.get("alias")), breakable(a.get("path"))
                )
            )
        out.append("\\end{longtable}")
        out.append("")
    return "\n".join(out)


# --------------------------------------------------------------------------


def graph_stats() -> dict:
    path = ROOT / "index/graph.jsonl"
    kinds = collections.Counter()
    n = 0
    if path.exists():
        for line in path.open(encoding="utf-8"):
            n += 1
            try:
                d = json.loads(line)
            except json.JSONDecodeError:
                continue
            if d.get("kind"):
                kinds[d["kind"]] += 1
    return {"lines": n, "kinds": kinds}


def main() -> int:
    OUT.mkdir(parents=True, exist_ok=True)

    ds = load("ledger/derivation_statements.yaml")
    docs = ds["documents"]
    theorems = load("ledger/theorems.yaml")["theorems"]
    symbols = load("ledger/symbols.yaml")["symbols"]
    aliases = load("ledger/documents.yaml")["aliases"]
    notes = load("ledger/notes.yaml")

    v1 = read_manifest("literature/library/paper_manifest.csv")
    v2 = read_manifest("literature/library/volume2/paper_manifest.csv")
    extraction, xstats = make_extraction()
    g = graph_stats()

    n_deriv = sum(len(d.get("statements") or []) for d in docs)
    n_open = sum(
        1
        for d in docs
        for s in (d.get("statements") or [])
        if s.get("status") in ("open", "conditional", "disputed")
    )
    locations = lean_locations()
    n_lean_modules = len({v.split(":")[0] for v in locations.values()})

    artefacts = {
        "gen_concordance.tex": make_concordance(docs),
        "gen_open_statements.tex": make_open_statements(docs),
        "gen_lean.tex": make_lean(theorems, locations),
        "gen_library.tex": make_library(v1, v2),
        "gen_extraction.tex": extraction,
        "gen_symbols.tex": make_symbols(symbols),
        "gen_documents.tex": make_documents(aliases),
        "gen_srcmacros.tex": "\n".join(
            header(
                "% Counts for the source-provenance sections.",
                f"\\newcommand{{\\CiteDocs}}{{{len(docs)}}}",
                f"\\newcommand{{\\DerivStatements}}{{{n_deriv}}}",
                f"\\newcommand{{\\DerivOpen}}{{{n_open}}}",
                f"\\newcommand{{\\LeanModules}}{{{n_lean_modules}}}",
                f"\\newcommand{{\\LibraryPapers}}{{{len(v1) + len(v2)}}}",
                f"\\newcommand{{\\LibraryVolOne}}{{{len(v1)}}}",
                f"\\newcommand{{\\LibraryVolTwo}}{{{len(v2)}}}",
                f"\\newcommand{{\\ExtractedPages}}{{{xstats['pages']}}}",
                f"\\newcommand{{\\ExtractedWorks}}{{{xstats['papers']}}}",
                f"\\newcommand{{\\ExtractedTopics}}{{{xstats['topics']}}}",
                f"\\newcommand{{\\SymbolCount}}{{{len(symbols)}}}",
                f"\\newcommand{{\\AliasCount}}{{{len(aliases)}}}",
                f"\\newcommand{{\\NoteArchives}}{{{len(notes.get('archives') or [])}}}",
                f"\\newcommand{{\\NoteReviews}}{{{len(notes.get('reviews') or [])}}}",
                f"\\newcommand{{\\GraphEdges}}{{{g['lines']}}}",
                f"\\newcommand{{\\GraphEdgeKinds}}{{{len(g['kinds'])}}}",
            )
        ),
    }

    for name, body in artefacts.items():
        (OUT / name).write_text(body + "\n", encoding="utf-8")
        print(f"wrote {name}: {len(body.splitlines())} lines")

    print(
        f"\nsources: {len(docs)} cite docs / {n_deriv} deriv statements "
        f"({n_open} not proven), {len(theorems)} lean theorems "
        f"({len(locations)} located), {len(v1) + len(v2)} library papers, "
        f"{xstats['pages']} extracted pages, {len(symbols)} symbols, "
        f"{len(aliases)} aliases, {g['lines']} graph edges"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
