#!/usr/bin/env python3
"""Extract every \\chk{...} marker from the paper source, grouped by section,
into coverage_generated.tex, so the machine-check coverage claim of the
Reproducibility section is auditable in print rather than asserted.

Run after any edit to the .tex, before rebuilding:  python3 make_coverage.py
"""

import re
import sys

SRC = "workhouse_publication_edition_v2_2026-08-30.tex"
OUT = "coverage_generated.tex"


def chk_bodies(text):
    """Yield (offset, body) for each \\chk{...}, counting nested braces."""
    for m in re.finditer(r"\\chk\{", text):
        depth, i = 1, m.end()
        while depth:
            if text[i] == "{":
                depth += 1
            elif text[i] == "}":
                depth -= 1
            i += 1
        yield m.start(), text[m.end() : i - 1]


def main():
    with open(SRC, encoding="utf-8") as fh:
        text = fh.read()
    # ignore the macro definition itself and anything before the abstract
    body_start = text.index(r"\begin{abstract}")
    sections = [(0, "Abstract")]
    for m in re.finditer(r"\\(?:sub)?section\*?(?:\[[^]]*\])?\{((?:[^{}]|\{[^{}]*\})*)\}", text):
        if m.start() > body_start:
            sections.append((m.start(), m.group(1)))
    grouped, order = {}, []
    for off, body in chk_bodies(text):
        if off < body_start:
            continue
        sec = max((s for s in sections if s[0] <= off), key=lambda s: s[0])[1]
        if sec not in grouped:
            grouped[sec] = []
            order.append(sec)
        grouped[sec].append(body.strip())
    n = sum(len(v) for v in grouped.values())
    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write("% generated by make_coverage.py -- do not edit\n")
        fh.write(
            f"The source carries {n} inline markers. Each line below is one "
            "marker, verbatim, under the section that carries it.\n\n"
        )
        fh.write("\\begin{itemize}\\footnotesize\\itemsep1pt\n")
        for sec in order:
            fh.write(f"\\item[] \\textbf{{{sec}}}\n\\begin{{itemize}}\\itemsep0pt\n")
            for body in grouped[sec]:
                fh.write(f"  \\item {body.replace(chr(0x2014), '---')}\n")
            fh.write("\\end{itemize}\n")
        fh.write("\\end{itemize}\n")
    print(f"{n} markers across {len(order)} sections -> {OUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
